Description of dropShortIntervals
Home > @intervalSet > dropShortIntervals.m
dropShortIntervals
PURPOSE
Drops the intervals in the set that are shorter than a given threshold
SYNOPSIS
function iso = dropShortIntervals(is, thr, varargin)
DESCRIPTION
  Drops the intervals in the set that are shorter than a given threshold
      USAGE:
      iso = dropShortIntervals(is, thr, OptionName, OptionValue)
      INPUTS:
      is  - an intervalSet
      thr - a duration threshold; all intervals shorter than thr will be
            dropped
      OUTPUTS:
      iso - the resulting intervalSet
CROSS-REFERENCE INFORMATION
This function calls:
End Ending time of the intervalSet object
Start Starting times of for each interval in the set
intervalSet Constructor for intervalSet objects
This function is called by:
mergeCloseIntervals Merge together intervals that are closer than a given threshold
SOURCE CODE
function iso = dropShortIntervals(is, thr, varargin)
%  Drops the intervals in the set that are shorter than a given threshold
%
%      USAGE:
%      iso = dropShortIntervals(is, thr, OptionName, OptionValue)
%
%      INPUTS:
%      is  - an intervalSet
%      thr - a duration threshold; all intervals shorter than thr will be
%            dropped
%
%      OUTPUTS:
%      iso - the resulting intervalSet
% copyright (c) 2004 Francesco P. Battaglia
% This software is released under the GNU GPL
% www.gnu.org/copyleft/gpl.html
  opt_varargin = varargin;
  defined_options = dictArray( ...
  { { 'TimeUnits', {time_units('ts'), {'char', 'units'} } } } );
  getOpt;
  cnvrt = convert(TimeUnits, is.units);
  thr = thr * cnvrt;
  st = Start(is);
  en = End(is);
  d = en-st;
  ix = find(d > thr);
  iso = intervalSet(st(ix), en(ix));