Description of Start
Home > @intervalSet > Start.m
Start
PURPOSE
Starting times of for each interval in the set
SYNOPSIS
function S = Start(O, TimeUnits)
DESCRIPTION
  Starting times of for each interval in the set
      USAGE:
      S = Start(O, TimeUnits)
      INPUTS:
      O - an intervalSet object
      TimeUnits (optionnal) - a units object or the abbreviation string
      OUTPUT:
      S = an array of starting points for each interval in the set
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
belong Tells whether timestamps belong to a intervalSet
cat Concatenates IntervalSet objects
diff Computes the set difference of intervalSet's
dropLongIntervals Drops the intervals in the set that are longer than a given threshold
dropShortIntervals Drops the intervals in the set that are shorter than a given threshold
inInterval Tells whether points are contained in intervalSet (TODO)
length Returns the length of each interval in the set
regIntervals Split an intervalSet object in N segments of equal length
timeSpan Returns the minimum continuous interval that contains the intervalSet
tot_length Returns total length of intervalSet
union Computes the union of intervalSet's
SOURCE CODE
function S = Start(O, TimeUnits)
%  Starting times of for each interval in the set
%
%      USAGE:
%      S = Start(O, TimeUnits)
%
%      INPUTS:
%      O - an intervalSet object
%      TimeUnits (optionnal) - a units object or the abbreviation string
%
%      OUTPUT:
%      S = an array of starting points for each interval in the set
% copyright (c) 2004 Francesco P. Battaglia
% This software is released under the GNU GPL
% www.gnu.org/copyleft/gpl.html
  if nargin < 1 | nargin > 2
    error('Call with one or two arguments');
  end
  if nargin == 1
    TimeUnits = time_units('ts');
  end
  S = O.start;
  if isa(TimeUnits, 'char')
    TimeUnits = time_units(TimeUnits);
  end
  cnvrt = convert(O.units, TimeUnits);
  if cnvrt ~= 1
    S = S * cnvrt;
  end