Description of residuals
residuals
PURPOSE
Residuals (or a few other things) from a locfit() fit.
SYNOPSIS
function y = residuals(fit,type)
DESCRIPTION
 Residuals (or a few other things) from a locfit() fit.
 Input arguments:
   fit - the locfit() fit.
   type (optional) type of residuals. Valid types are
     'dev'    (deviance, the default)
     'd2'     (deviance squared)
     'pearson'(Pearson)
     'raw'    (observed - fitted)
     'ldot'   (derivative of log-likelihood)
     'lddot'  (second derivative)
     'fit'    (fitted values - no transformation)
     'mean'   (fitted values - with back transformation)
  Author: Catherine Loader.
CROSS-REFERENCE INFORMATION
This function calls:
predict Interpolate a fit produced by locfit().
This function is called by:
fig2_5 Local Regression and Likelihood, Figure 2.5.
fig4_3 Local Regression and Likelihood, Figure 4.3.
fig6_3 Local Regression and Likelihood, Figure 6.3.
fig6_4 Local Regression and Likelihood, Figure 6.4.
SOURCE CODE
function y = residuals(fit,type)
% Residuals (or a few other things) from a locfit() fit.
%
% Input arguments:
%   fit - the locfit() fit.
%   type (optional) type of residuals. Valid types are
%     'dev'    (deviance, the default)
%     'd2'     (deviance squared)
%     'pearson'(Pearson)
%     'raw'    (observed - fitted)
%     'ldot'   (derivative of log-likelihood)
%     'lddot'  (second derivative)
%     'fit'    (fitted values - no transformation)
%     'mean'   (fitted values - with back transformation)
%
%  Author: Catherine Loader.
if (nargin<2) type = 'dev'; end;
y = predict(fit,'d','restyp',type);
return;