Description of wave_browser
wave_browser
PURPOSE
WAVE_BROWSER M-file for wave_browser.fig
SYNOPSIS
function varargout = wave_browser(varargin)
DESCRIPTION
 WAVE_BROWSER M-file for wave_browser.fig
      WAVE_BROWSER, by itself, creates a new WAVE_BROWSER or raises the existing
      singleton*.
      H = WAVE_BROWSER returns the handle to a new WAVE_BROWSER or the handle to
      the existing singleton*.
      WAVE_BROWSER('CALLBACK',hObject,eventData,handles,...) calls the local
      function named CALLBACK in WAVE_BROWSER.M with the given input arguments.
      WAVE_BROWSER('Property','Value',...) creates a new WAVE_BROWSER or raises the
      existing singleton*.  Starting from the left, property value pairs are
      applied to the GUI before wave_browser_OpeningFunction gets called.  An
      unrecognized property name or invalid value makes property application
      stop.  All inputs are passed to wave_browser_OpeningFcn via varargin.
      *See GUI Options on GUIDE's Tools menu.  Choose "GUI allows only one
      instance to run (singleton)".
 See also: GUIDE, GUIDATA, GUIHANDLES
CROSS-REFERENCE INFORMATION
This function calls:
close VR=CLOSE(VR)
close VW=CLOSE(VW)
close VR=CLOSE(VR)
close VW=CLOSE(VW)
close VR=CLOSE(VR)
close VW=CLOSE(VW)
mtdspecgramc Multi-taper derivative of the time-frequency spectrum - continuous process
mtspecgramc Multi-taper time-frequency spectrum - continuous process
This function is called by:
SUBFUNCTIONS
function wave_browser_OpeningFcn(hObject, eventdata, handles, varargin)
function varargout = wave_browser_OutputFcn(hObject, eventdata, handles)
function Frequency_Callback(hObject, eventdata, handles)
function Frequency_CreateFcn(hObject, eventdata, handles)
function LoadFile_Callback(hObject, eventdata, handles)
function [wavesize channels] = wavsizeget(filename);
function handles = loadfile(hObject, eventdata, handles, varargin)
function endian_Callback(hObject, eventdata, handles)
function endian_CreateFcn(hObject, eventdata, handles)
function edit2_Callback(hObject, eventdata, handles)
function edit2_CreateFcn(hObject, eventdata, handles)
function FileNameString_Callback(hObject, eventdata, handles)
function FileNameString_CreateFcn(hObject, eventdata, handles)
function WinSize_Callback(hObject, eventdata, handles)
function WinSize_CreateFcn(hObject, eventdata, handles)
function slider1_Callback(hObject, eventdata, handles)
function slider1_CreateFcn(hObject, eventdata, handles)
function StepSize_Callback(hObject, eventdata, handles)
function StepSize_CreateFcn(hObject, eventdata, handles)
function TW_Callback(hObject, eventdata, handles)
function TW_CreateFcn(hObject, eventdata, handles)
function DisplayWindow_Callback(hObject, eventdata, handles)
function DisplayWindow_CreateFcn(hObject, eventdata, handles)
function indexinS = getindexpre_c(t,timestart,timeend)
function Plot_Callback(hObject, eventdata, handles)
function [Stot boxcurve] = compute_threshold_free(S,th,n)
function [ratiof boxcurve] = compute_index(S,lower_range,upper_range,lowerfreq,upperfreq,indexthresh,n)
function smoothedcurve = smooth_curve(curve2smooth,n);
function MinFreq_Callback(hObject, eventdata, handles)
function MinFreq_CreateFcn(hObject, eventdata, handles)
function MaxFreq_Callback(hObject, eventdata, handles)
function MaxFreq_CreateFcn(hObject, eventdata, handles)
function SpectrumType_Callback(hObject, eventdata, handles)
function SpectrumType_CreateFcn(hObject, eventdata, handles)
function AmpThresh_Callback(hObject, eventdata, handles)
function AmpThresh_CreateFcn(hObject, eventdata, handles)
function TDerThresh_Callback(hObject, eventdata, handles)
function TDerThresh_CreateFcn(hObject, eventdata, handles)
function PlayAll_Callback(hObject, eventdata, handles)
function PlayWindow_Callback(hObject, eventdata, handles)
function txt = datacursorfunc(empt,event_obj)
function handles = draw_segments(handles)
function SegmentButton_Callback(hObject, eventdata, handles)
function SegStartButton_Callback(hObject, eventdata, handles)
function SegEndButton_Callback(hObject, eventdata, handles)
function out=draw_all_x(handles, segment)
function out=draw_x(theaxes, segment)
function JumpBack_Callback(hObject, eventdata, handles)
function Jump_Callback(hObject, eventdata, handles)
function Jump_shared(hObject, eventdata, handles, jump_dir)
function LoadNext_Callback(hObject, eventdata, handles)
function Precompute_Callback(hObject, eventdata, handles)
function Precompute_CreateFcn(hObject, eventdata, handles)
function Path_Callback(hObject, eventdata, handles)
function Path_CreateFcn(hObject, eventdata, handles)
function Extensions_Callback(hObject, eventdata, handles)
function Extensions_CreateFcn(hObject, eventdata, handles)
function Duration_CreateFcn(hObject, eventdata, handles)
function LoadSegments_Callback(hObject, eventdata, handles)
function handles=load_segment(handles,filename)
function filteredsegments = filtersegments(handles,segments)
function ExcludeExt_Callback(hObject, eventdata, handles)
function ExcludeExt_CreateFcn(hObject, eventdata, handles)
function DeleteSegment_Callback(hObject, eventdata, handles)
function handles=delete_segment(handles, n)
function SaveSegments_Callback(hObject, eventdata, handles)
function handles=savesegments2mem(handles)
function SegCancel_Callback(hObject, eventdata, handles)
function PlotSegments_Callback(hObject, eventdata, handles)
function AutoSegButton_Callback(hObject, eventdata, handles)
function DeleteAllButton_Callback(hObject, eventdata, handles)
function PlotAllButton_Callback(hObject, eventdata, handles)
function PreviousChunk_Callback(hObject, eventdata, handles)
function NextChunk_Callback(hObject, eventdata, handles)
function AutoSegmentFile_Callback(hObject, eventdata, handles)
function MaxSegLength_Callback(hObject, eventdata, handles)
function MaxSegLength_CreateFcn(hObject, eventdata, handles)
function MaximumWavSize_Callback(hObject, eventdata, handles)
function MaximumWavSize_CreateFcn(hObject, eventdata, handles)
function SeekButton_Callback(hObject, eventdata, handles)
function SeektoEdit_Callback(hObject, eventdata, handles)
function SeektoEdit_CreateFcn(hObject, eventdata, handles)
function RealDuration_Callback(hObject, eventdata, handles)
function RealDuration_CreateFcn(hObject, eventdata, handles)
function AutoMethodPopupMenu_Callback(hObject, eventdata, handles)
function AutoMethodPopupMenu_CreateFcn(hObject, eventdata, handles)
function RatioThresh_Callback(hObject, eventdata, handles)
function RatioThresh_CreateFcn(hObject, eventdata, handles)
function RatioLower_Callback(hObject, eventdata, handles)
function RatioLower_CreateFcn(hObject, eventdata, handles)
function RatioUpper_Callback(hObject, eventdata, handles)
function RatioUpper_CreateFcn(hObject, eventdata, handles)
function OptionsDisplay_Callback(hObject, eventdata, handles)
function Duration_Callback(hObject, eventdata, handles)
function SmoothFactor_Callback(hObject, eventdata, handles)
function SmoothFactor_CreateFcn(hObject, eventdata, handles)
function channel_Callback(hObject, eventdata, handles)
function channel_CreateFcn(hObject, eventdata, handles)
SOURCE CODE
function varargout = wave_browser(varargin)
% WAVE_BROWSER M-file for wave_browser.fig
%      WAVE_BROWSER, by itself, creates a new WAVE_BROWSER or raises the existing
%      singleton*.
%
%      H = WAVE_BROWSER returns the handle to a new WAVE_BROWSER or the handle to
%      the existing singleton*.
%
%      WAVE_BROWSER('CALLBACK',hObject,eventData,handles,...) calls the local
%      function named CALLBACK in WAVE_BROWSER.M with the given input arguments.
%
%      WAVE_BROWSER('Property','Value',...) creates a new WAVE_BROWSER or raises the
%      existing singleton*.  Starting from the left, property value pairs are
%      applied to the GUI before wave_browser_OpeningFunction gets called.  An
%      unrecognized property name or invalid value makes property application
%      stop.  All inputs are passed to wave_browser_OpeningFcn via varargin.
%
%      *See GUI Options on GUIDE's Tools menu.  Choose "GUI allows only one
%      instance to run (singleton)".
%
% See also: GUIDE, GUIDATA, GUIHANDLES
% Copyright 2002-2003 The MathWorks, Inc.
% Edit the above text to modify the response to help wave_browser
% Last Modified by GUIDE v2.5 29-May-2007 16:30:52
% Begin initialization code - DO NOT EDIT
gui_Singleton = 1;
gui_State = struct('gui_Name',       mfilename, ...
                   'gui_Singleton',  gui_Singleton, ...
                   'gui_OpeningFcn', @wave_browser_OpeningFcn, ...
                   'gui_OutputFcn',  @wave_browser_OutputFcn, ...
                   'gui_LayoutFcn',  [] , ...
                   'gui_Callback',   []);
if nargin && ischar(varargin{1})
    gui_State.gui_Callback = str2func(varargin{1});
end
if nargout
    [varargout{1:nargout}] = gui_mainfcn(gui_State, varargin{:});
else
    gui_mainfcn(gui_State, varargin{:});
end
% End initialization code - DO NOT EDIT
% --- Executes just before wave_browser is made visible.
function wave_browser_OpeningFcn(hObject, eventdata, handles, varargin)
% This function has no output args, see OutputFcn.
% hObject    handle to figure
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    structure with handles and user data (see GUIDATA)
% varargin   command line arguments to wave_browser (see VARARGIN)
handles.firsttime = 0; % indicates the firsttime that segment has been precomputed
handles.precomputed_spec = 0; % indicates that the spectra has not been precomputed
handles.longfile = 0;  % indicates whether the file is a long file
handles.maxwavsize = 10 * 44100; % I will have to explore what number works best here
handles.maxspec_t = 30; % duration of the max size of a spectra
handles.Fs = 44100; % default size to start with
handles.segments = []; % holds regular segments in the current chunk
handles.allsegments = []; % holds segments across the maximum wave size
handles.loadedsegment = 0; % indicates no segments have been loaded
handles.lastmarkerstart = 1; % largest segment
handles.segmentmode = 0; % by default start off with segmenting turned off
handles.dontcutsegments = 0; % by default do not adapt to segments
handles.automethod = 'threshold'; % use threshold or ratiof method
handles.indexthresh = 10; % for ration method the threshold which to cut the curve off
handles.lower_range = [10 10000];  % the numerator in the ratio
handles.upper_range = [15000 20000]; % the denomitor in the ratio
handles.nsmooth = 0; % moving average parameter for the thresholds curves
positionP = get(handles.OptionsUiPanel,'Position');
positionF = get(gcf,'Position');
positionF(3) = positionF(3) - positionP(3);
% set(gcf,'Position',positionF); % untested
% Choose default command line output for wave_browser
handles.output = hObject;
% Update handles structure
guidata(hObject, handles);
% UIWAIT makes wave_browser wait for user response (see UIRESUME)
% uiwait(handles.figure1);
% --- Outputs from this function are returned to the command line.
function varargout = wave_browser_OutputFcn(hObject, eventdata, handles)
% Get default command line output from handles structure
varargout{1} = handles.output;
function Frequency_Callback(hObject, eventdata, handles)
handles.Fs = eval(get(hObject,'String'));
guidata(gcbo,handles);
function Frequency_CreateFcn(hObject, eventdata, handles)
set(hObject,'String', '44100');
handles.Fs = 44100;
guidata(gcbo,handles);
if ispc
    set(hObject,'BackgroundColor','white');
else
    set(hObject,'BackgroundColor',get(0,'defaultUicontrolBackgroundColor'));
end
% --- Executes on button press in LoadFile.
function LoadFile_Callback(hObject, eventdata, handles)
[fname pname]=uigetfile({'*.wav';'*.*'},'Load Time Series');
if fname == 0
    return
end
set(handles.FileNameString, 'String',fname);
handles.filename = [pname fname];
[path] = cell2mat(regexp(handles.filename, '^.*\', 'match'));
[extension] = cell2mat(regexp(handles.filename, '\w+$', 'match'));
set(handles.Path,'String',path);
% set(handles.Extensions,'String',extension);
handles.segments = [];
handles.allsegments = [];
handles = loadfile(hObject, eventdata, handles);
guidata(hObject,handles);
function [wavesize channels] = wavsizeget(filename);
% Provides usable information about a file
    wavesize = 0;
    [filestatus info] = wavfinfo(filename);
    info = regexp(info,'[0-9]+','match');
    channels = str2num(info{2});
    wavesize = str2num(info{1});
function handles = loadfile(hObject, eventdata, handles, varargin)
% Function for loading a file or using the optional varargin to load a
% specified position and size in the file
% contents=get(handles.endian,'String');
% precision=contents{get(handles.endian,'Value')};
[datasize channels] = wavsizeget(handles.filename);
handles.wavsize = datasize; % total number of samples in the files
try
    handles.maxwavsize = round(handles.Fs * str2num(get(handles.MaximumWavSize,'String')));
catch
    handles.maxwavsize = 20;
    set(handles.MaximumWavSize,'String',num2str(handles.maxwavsize));
    handles.maxwavsize = handles.maxwavsize * handles.Fs;
end
if isempty(varargin)
    handles.markerstart = 1;
    if datasize > handles.maxwavsize
        handles.markerend = handles.maxwavsize;
        handles.longfile = 1; % indicates that the file is long and will be loaded in chunks
    else
        handles.markerend = datasize;
    end
else % passed in optional parameter
    handles.markervec = varargin{1};
    handles.markerstart = handles.markervec(1);
    handles.markerend = handles.markervec(2);
end
if handles.markerstart <= 1 % make sure the range is possible
    handles.markerstart = 1;
    set(handles.PreviousChunk,'Enable','off');
else
    set(handles.PreviousChunk,'Enable','on');
end
if handles.markerend >= handles.wavsize
    handles.markerend = handles.wavsize;
    set(handles.NextChunk,'Enable','off');
else
    set(handles.NextChunk,'Enable','on');
end
if handles.maxwavsize < handles.wavsize
   total_chunk = ceil(handles.wavsize / handles.maxwavsize);
   i = 1;
   while (i < total_chunk) &&  (handles.markerend >= (handles.maxwavsize * i))
       i = i + 1;
   end
   current_chunk = i-1;
   if handles.markerend == handles.wavsize
       current_chunk = total_chunk;
   end
   set(handles.ChunkText,'String',['Chunk ' num2str(current_chunk) '/' num2str(total_chunk)]);
end
try
    handles.maxseglength = round(handles.Fs * str2num(get(handles.MaxSegLength,'String')));
catch
    handles.maxseglength = handles.Fs * 1;
end
set(handles.RealDuration,'String',num2str(handles.wavsize/handles.Fs,'%.1f'));
if handles.segmentmode % only if in segment mode make sure segments are not cut
    if (handles.markerstart - handles.lastmarkerstart > 0) % only do this in terms of forward movement
        if handles.dontcutsegments % this code is added so segments are not cut off when segmenting
            if not(isempty(handles.segments)) % at least one segment has been defined previously
                maxsegend = handles.segments(1).end; % find last defined segment in previous view
                for i = 2:length(handles.segments)
                    if handles.segments(i).end > maxsegend
                        maxsegend = handles.segments(i).end;
                    end
                end
                maxsegend = round(maxsegend * handles.Fs);
                if (handles.lastmarkerend - maxsegend) < (handles.lastmarkerend - handles.maxseglength)
                    handles.markerstart = (handles.lastmarkerstart + maxsegend) + 1; % defined segment is closer to the end
                else
                    handles.markerstart = handles.lastmarkerend - handles.maxseglength;
                end
            else
                handles.markerstart = handles.lastmarkerend - handles.maxseglength;
            end
            handles.markerend = handles.markerstart + handles.maxwavsize - 1;
            if handles.markerend > handles.wavsize
                handles.markerend = handles.wavsize;
            end
        end
    end
end
hw=waitbar(0,'Loading ...'); waitbar(0.5,hw); drawnow;
[handles.markerstart handles.markerend]/handles.Fs
[handles.ts,handles.Fs] = wavread(handles.filename, [handles.markerstart handles.markerend]);
channel = str2double(get(handles.channel,'String'));
handles.ts = handles.ts(:,channel);
count = length(handles.ts);
handles.ts = handles.ts/std(handles.ts); % variance normalisation
set(handles.Frequency,'String', num2str(handles.Fs));
set(handles.Duration, 'String', count/handles.Fs);
Tim=eval(get(handles.DisplayWindow,'String'));
display_frac = 1;%max(1,Tim*handles.Fs/count);
set(handles.slider1, 'Value', 0);
set(handles.SegmentButton, 'Enable', 'on');
if handles.longfile
    set(handles.SeekButton,'Enable', 'on');
end
set(handles.LoadNext, 'Enable', 'on');
set(handles.PlayAll, 'Enable', 'on');
set(handles.PlayWindow, 'Enable', 'on');
set(handles.Plot, 'Enable', 'on');
set(handles.PlotAllButton, 'Enable', 'on');
set(handles.Precompute, 'Enable','on');
set(handles.Jump,'Enable','on');
set(handles.JumpBack,'Enable','on');
handles.segments = []; % remove the current segments
handles.segments = filtersegments(handles,handles.allsegments);
set(handles.Precompute,'Value',1); % Set into precompute mode
Precompute_Callback(handles.Precompute, eventdata, handles);
handles = guidata(gcbo);
% set(handles.Precompute,'Value',1);
handles.precomputed_spec = 1;
handles.dontcutsegments = 1; % make sure segments are not cut off
handles.lastmarkerstart = handles.markerstart;
handles.lastmarkerend = handles.markerend;
close(hw);
% guidata(gcbo,handles);
% Plot_Callback(hObject, eventdata, handles);
% --- Executes on selection change in endian.
function endian_Callback(hObject, eventdata, handles)
% --- Executes during object creation, after setting all properties.
function endian_CreateFcn(hObject, eventdata, handles)
if ispc
    set(hObject,'BackgroundColor','white');
else
    set(hObject,'BackgroundColor',get(0,'defaultUicontrolBackgroundColor'));
end
function edit2_Callback(hObject, eventdata, handles)
function edit2_CreateFcn(hObject, eventdata, handles)
if ispc
    set(hObject,'BackgroundColor','white');
else
    set(hObject,'BackgroundColor',get(0,'defaultUicontrolBackgroundColor'));
end
function FileNameString_Callback(hObject, eventdata, handles)
function FileNameString_CreateFcn(hObject, eventdata, handles)
if ispc
    set(hObject,'BackgroundColor','white');
else
    set(hObject,'BackgroundColor',get(0,'defaultUicontrolBackgroundColor'));
end
function WinSize_Callback(hObject, eventdata, handles)
function WinSize_CreateFcn(hObject, eventdata, handles)
if ispc
    set(hObject,'BackgroundColor','white');
else
    set(hObject,'BackgroundColor',get(0,'defaultUicontrolBackgroundColor'));
end
% --- Executes on slider movement.
function slider1_Callback(hObject, eventdata, handles)
function slider1_CreateFcn(hObject, eventdata, handles)
usewhitebg = 1;
if usewhitebg
    set(hObject,'BackgroundColor',[.9 .9 .9]);
else
    set(hObject,'BackgroundColor',get(0,'defaultUicontrolBackgroundColor'));
end
function StepSize_Callback(hObject, eventdata, handles)
function StepSize_CreateFcn(hObject, eventdata, handles)
if ispc
    set(hObject,'BackgroundColor','white');
else
    set(hObject,'BackgroundColor',get(0,'defaultUicontrolBackgroundColor'));
end
function TW_Callback(hObject, eventdata, handles)
function TW_CreateFcn(hObject, eventdata, handles)
if ispc
    set(hObject,'BackgroundColor','white');
else
    set(hObject,'BackgroundColor',get(0,'defaultUicontrolBackgroundColor'));
end
function DisplayWindow_Callback(hObject, eventdata, handles)
function DisplayWindow_CreateFcn(hObject, eventdata, handles)
set(hObject, 'String', '4');
if ispc
    set(hObject,'BackgroundColor','white');
else
    set(hObject,'BackgroundColor',get(0,'defaultUicontrolBackgroundColor'));
end
%function axes2ButtonDownCallback(hObject, eventdata, handles)
%h=handles.axesS; P=get(h,'CurrentPoint');
%fprintf('worked %f %f!\n', P(1),P(2));
function indexinS = getindexpre_c(t,timestart,timeend)
% A function for indexing correctly in time to a spectra stored in memory
tlen = length(t);
i=1;
while (i <= tlen) && (t(i) < timestart)
    i = i + 1;
end
firstindex = i;
while (i <= tlen) && (t(i) < timeend)
    i = i + 1;
end
secondindex = i;
indexinS = [firstindex secondindex];
% --- Executes on button press in Plot.
function Plot_Callback(hObject, eventdata, handles)
hw=waitbar(0.5,'Spectrogram calculation');drawnow
params.Fs=handles.Fs;
window=eval(get(handles.WinSize,'String'));
winstep=eval(get(handles.StepSize,'String'));
movingwin=[window winstep]*0.001;
fmin=eval(get(handles.MinFreq,'String'));
fmax=eval(get(handles.MaxFreq,'String'));
params.fpass=[fmin fmax];
p=eval(get(handles.TW,'String'));
params.tapers=[p floor(2*p-1)];
params.pad=1;
Tslider=get(handles.slider1,'Value');
Tim=eval(get(handles.DisplayWindow,'String'));
NT=min(round(Tim*handles.Fs),length(handles.ts));
handles.Tmin=1+floor(Tslider*length(handles.ts));
handles.Tmax=min(handles.Tmin+NT,length(handles.ts));
if handles.Tmax < length(handles.ts)
    set( handles.Jump, 'Enable', 'on' );
else
    set( handles.Jump, 'Enable', 'off' );
end
if handles.Tmin > 1
    set( handles.JumpBack, 'Enable', 'on' );
else
    set( handles.JumpBack, 'Enable', 'off' );
end
data=handles.ts(handles.Tmin:handles.Tmax);data=data(:);
handles.upper_range =  eval(get(handles.RatioLower,'String'));
handles.lower_range  = eval(get(handles.RatioUpper,'String'));
handles.indexthresh =  eval(get(handles.RatioThresh,'String'));
handles.nsmooth = eval(get(handles.SmoothFactor,'String'));
% determine spectrum type
contents=get(handles.SpectrumType,'String');
stype=contents{get(handles.SpectrumType,'Value')};
axes(handles.axesW); plot(((handles.markerstart - 1)/handles.Fs) + [handles.Tmin:handles.Tmax]/handles.Fs,handles.ts(handles.Tmin:handles.Tmax)); axis tight;
switch stype
    case 'Original'
     if not(handles.precomputed_spec) || handles.firsttime
        [S,t,f]=mtspecgramc(diff(data),movingwin,params);
        timeax=(handles.Tmin/handles.Fs)+t;
     else
         indexinS = getindexpre_c(handles.t,(handles.Tmin-1)/handles.Fs,(handles.Tmax-1)/handles.Fs);
%          indexinS = round(([handles.Tmin-1, handles.Tmax-1]/handles.Fs)/movingwin(2))+1;
         if indexinS(1) < 1
             indexinS(1) = 1;
         end
         SLen = length(handles.S(:,1));
         if indexinS(2) > SLen
             indexinS(2) = SLen;
         end
         f = handles.f;
         t = handles.t(indexinS(1):indexinS(2));
         S = handles.S(indexinS(1):indexinS(2),:);
         timeax=t;
     end
    cmap='default';
    th=eval(get(handles.AmpThresh,'String'));
    % This sets up the automatic segmenting algorithm
    if strcmp(handles.automethod,'threshold')
        [Stot boxcurve] = compute_threshold_free(S,th,handles.nsmooth);
        axes(handles.axesP);
        semilogy(timeax,Stot);
        axis tight;
    elseif strcmp(handles.automethod,'ratiof')
        [ratiof boxcurve] = compute_index(S,handles.lower_range,handles.upper_range,fmin,fmax,handles.indexthresh,handles.nsmooth);
        axes(handles.axesP);
        semilogy(timeax,ratiof);
        axis tight;
    end
    hold on; semilogy(timeax,boxcurve,'r'); hold off;
    axes(handles.axesS);
    imagesc(timeax,f,log(S)'); axis xy; colormap(cmap);
    %imagesc(t,f,log(S)'); axis xy; colormap(cmap);
%    set(h,'ButtonDownFcn',axes2ButtonDownCallback);
    case 'Time Derivative'
    if not(handles.precomputed_spec) || handles.firsttime
        [S,t,f]=mtdspecgramc(diff(data),movingwin,0,params);S = S';
        timeax=handles.Tmin/handles.Fs+t;
    else
        indexinS = getindexpre_c(handles.t,(handles.Tmin-1)/handles.Fs,(handles.Tmax-1)/handles.Fs);
%          indexinS = round(([handles.Tmin-1, handles.Tmax-1]/handles.Fs)/movingwin(2))+1;
         if indexinS(1) < 1
             indexinS(1) = 1;
         end
         SLen = length(handles.S(1,:));
         if indexinS(2) > SLen
             indexinS(2) = SLen;
         end
         f = handles.f;
         t = handles.t(indexinS(1):indexinS(2));
         S = handles.S(:,indexinS(1):indexinS(2));
         timeax = t;
    end
    cmap='gray';
    th=eval(get(handles.TDerThresh,'String'));
    if strcmp(handles.automethod,'threshold')
        [Stot boxcurve] = compute_threshold_free(abs(S'),th.handles.nsmooth);
        axes(handles.axesP);
        semilogy(timeax,Stot);
        axis tight;
    elseif strcmp(handles.automethod,'ratiof')
        [ratiof boxcurve] = compute_index(abs(S)',handles.lower_range,handles.upper_range,fmin,fmax,handles.indexthresh,handles.nsmooth);
        axes(handles.axesP);
        semilogy(timeax,ratiof);
        axis tight;
    end
    hold on; semilogy(timeax,boxcurve,'r'); hold off;
    axes(handles.axesS);
    imagesc(timeax,f,S); axis xy; colormap(cmap);
    cmin=0.02*min(min(S)); cmax=0.02*max(max(S)); caxis([cmin cmax]);
    case 'Frequency Derivative'
    if not(handles.precomputed_spec) || handles.firsttime
        [S,t,f]=mtdspecgramc(diff(data),movingwin,pi/2,params);S=S';
        timeax=handles.Tmin/handles.Fs+t;
    else
        indexinS = getindexpre_c(handles.t,(handles.Tmin-1)/handles.Fs,(handles.Tmax-1)/handles.Fs);
         if indexinS(1) < 1
             indexinS(1) = 1;
         end
         SLen = length(handles.S(1,:));
         if indexinS(2) > SLen
             indexinS(2) = SLen;
         end
         f = handles.f;
         t = handles.t(indexinS(1):indexinS(2));
         S = handles.S(:,indexinS(1):indexinS(2));
         timeax = t;
    end
    cmap='gray';
    th=eval(get(handles.TDerThresh,'String'));
    if strcmp(handles.automethod,'threshold')
        [Stot boxcurve] = compute_threshold_free(abs(S'),th,handles.nsmooth);
        axes(handles.axesP);
        semilogy(timeax,Stot);
        axis tight;
    elseif strcmp(handles.automethod,'ratiof')
        [ratiof boxcurve] = compute_index(abs(S)',handles.lower_range,handles.upper_range,fmin,fmax,handles.indexthresh,handles.nsmooth);
        axes(handles.axesP);
        semilogy(timeax,ratiof);
        axis tight;
    end
    hold on; semilogy(timeax,boxcurve,'r'); hold off;
    axes(handles.axesS);
    imagesc(timeax,f,S); axis xy; colormap(cmap);
    cmin=0.02*min(min(S)); cmax=0.02*max(max(S)); caxis([cmin cmax]);
end;
if handles.firsttime % first time precomputing the spectra
    handles.S = S;
    handles.t = t;
    handles.f = f;
    handles.precomputed_spec = 1;
    handles.firstime = 0;
end
% S = log(S)';
% Smax = max(max(S));
% Smin = min(min(S));
% Ssmall = uint8(round(((S - Smin)/(Smax-Smin))*255));
%
%  save('uint8_test.mat','Ssmall','-mat');
%  save('full_rest.mat','S','-mat');
handles.times=timeax(:);
handles.transition=[diff(boxcurve(:)); 0];
set(handles.axesS, 'XTick', []);
set(handles.axesP, 'XTick', []);
if exist('handles.datacursor')
    delete( handles.datacursor );
    delete( handles.segmentLineP );
    delete( handles.segmentLineS );
    delete( handles.segmentLineW );
end
handles.datacursor=datacursormode(handles.figure1);
axes(handles.axesP);
handles.segmentLineP = line('Visible','off');
axes(handles.axesS);
handles.segmentLineS = line('Visible','off');
axes(handles.axesW);
handles.segmentLineW = line('Visible','off');
if get(handles.SegmentButton, 'Value')
    set(handles.datacursor,'Enable','on','DisplayStyle','datatip','SnapToDataVertex','off','UpdateFcn',@datacursorfunc);
end
guidata(gcbo,handles);
close(hw);
handles = draw_segments(handles);
function  [Stot boxcurve] = compute_threshold_free(S,th,n)
% Computes the threshold based on a floating percentage of the maximum
% summed intensity
    Stot=sum(S,2);
    boxcurve=Stot;
    smax=max(Stot);
    Stot = smooth_curve(Stot',n); % for removing extremes
    boxcurve(find(Stot<th*smax))= smax*th;
    boxcurve(find(Stot>th*smax))= smax;
function [ratiof boxcurve] = compute_index(S,lower_range,upper_range,lowerfreq,upperfreq,indexthresh,n)
    % This algorithm is based on the method described in Aylin's
    % dissertation.
    S = S';
    nfreqs = length(S(:,1));
    freqspern = (upperfreq - lowerfreq) / nfreqs;
    indexinlower = fliplr(nfreqs - round((lower_range - lowerfreq)/freqspern));
    indexinupper = fliplr(nfreqs - round((upper_range - lowerfreq)/freqspern)) + 1;
    nrangelower = indexinlower(2)-indexinlower(1);
    nrangeupper = indexinupper(2)-indexinupper(1);
    ratiof = ( sum(S(indexinupper(1) : indexinupper(2),:)) / nrangeupper )...
    ./ ( sum(S( indexinlower(1) : indexinlower(2),:)) / nrangelower );
    ratiof = smooth_curve(ratiof,n); % for smoothing the curve
    maxrf = max(ratiof);
    boxcurve = ratiof;
    boxcurve(find(ratiof<indexthresh))= indexthresh;
    boxcurve(find(ratiof>=indexthresh))= maxrf;
function smoothedcurve = smooth_curve(curve2smooth,n);
% Computes the moving average of the curve where n is an integer
% for example n = 1 averages the current point with the point before and afterwards
    m = length(curve2smooth);
    if m > 0
        curve2smooth = [repmat(curve2smooth(1),1,n) curve2smooth repmat(curve2smooth(m),1,n)];
        smoothedcurve = zeros(m,1);
        for i = 1:m
            smoothedcurve(i) = sum(curve2smooth(i:i + 2 * n)) / (2 * n + 1);
        end
    else % just to save computation time
        smoothed_curve = curve2smooth;
    end
function MinFreq_Callback(hObject, eventdata, handles)
function MinFreq_CreateFcn(hObject, eventdata, handles)
if ispc
    set(hObject,'BackgroundColor','white');
else
    set(hObject,'BackgroundColor',get(0,'defaultUicontrolBackgroundColor'));
end
function MaxFreq_Callback(hObject, eventdata, handles)
function MaxFreq_CreateFcn(hObject, eventdata, handles)
if ispc
    set(hObject,'BackgroundColor','white');
else
    set(hObject,'BackgroundColor',get(0,'defaultUicontrolBackgroundColor'));
end
% --- Executes on selection change in SpectrumType.
function SpectrumType_Callback(hObject, eventdata, handles)
function SpectrumType_CreateFcn(hObject, eventdata, handles)
if ispc
    set(hObject,'BackgroundColor','white');
else
    set(hObject,'BackgroundColor',get(0,'defaultUicontrolBackgroundColor'));
end
function AmpThresh_Callback(hObject, eventdata, handles)
function AmpThresh_CreateFcn(hObject, eventdata, handles)
if ispc
    set(hObject,'BackgroundColor','white');
else
    set(hObject,'BackgroundColor',get(0,'defaultUicontrolBackgroundColor'));
end
function TDerThresh_Callback(hObject, eventdata, handles)
% --- Executes during object creation, after setting all properties.
function TDerThresh_CreateFcn(hObject, eventdata, handles)
if ispc
    set(hObject,'BackgroundColor','white');
else
    set(hObject,'BackgroundColor',get(0,'defaultUicontrolBackgroundColor'));
end
% --- Executes on button press in PlayAll.
function PlayAll_Callback(hObject, eventdata, handles)
wavplay(handles.ts,handles.Fs);
% --- Executes on button press in PlayWindow.
function PlayWindow_Callback(hObject, eventdata, handles)
wavplay(handles.ts(handles.Tmin:handles.Tmax),handles.Fs,'async');
%h=handles.axesP; axes(h); semilogy(timeax,Stot); axis tight;
function txt = datacursorfunc(empt,event_obj)
pos = get(event_obj,'Position');
handles=guidata(get(event_obj,'Target'));
  set(handles.segmentLineP,'Xdata',[pos(1) pos(1)],'Ydata',[0.00000000000001*pos(2) 1000000000000*pos(2)],'Visible','on' );
  set(handles.segmentLineS,'Xdata',[pos(1) pos(1)],'Ydata',[0.00000000000001*pos(2) 1000000000000*pos(2)],'Visible','on' );
  set(handles.segmentLineW,'Xdata',[pos(1) pos(1)],'Ydata',[-100000000000*pos(2) 1000000000000*pos(2)],'Visible','on' );
  if handles.start_stop_enable == 1
      set( handles.SegStartButton, 'Enable', 'on' );
  else
      set( handles.SegEndButton, 'Enable', 'on' );
  end
txt = {[num2str(pos(1))]};
guidata(gcbo,handles);
function handles = draw_segments(handles)
n = 1;
while n <= length(handles.segments)
    handles.segments(n).lines=[];
    handles.segments(n) = draw_all_x( handles, handles.segments(n) );
    n = n + 1;
end
guidata(gcbo,handles);
% --- Executes on button press in SegmentButton.
function SegmentButton_Callback(hObject, eventdata, handles)
toggled = get(handles.SegmentButton, 'Value');
if toggled
    handles.segments = [];
    handles.segmentmode = 1;
    set( handles.SegmentButton, 'String', 'Segment On' );
    set( handles.SegmentButton, 'Enable', 'off' );
    if not(exist([handles.filename '.seg.txt']));
        set( handles.LoadSegments, 'Enable', 'off' );
    else
        set( handles.LoadSegments, 'Enable', 'on' );
    end
    set( handles.AutoSegmentFile, 'Enable','on');
    set( handles.AutoSegButton, 'Enable', 'on' );
    set( handles.SegmentLengthEdit, 'Enable', 'on' );
    set( handles.SegmentLengthText, 'Enable', 'on ' );
    set( handles.SaveSegments, 'Enable', 'on' );
    set( handles.DeleteSegment, 'Enable', 'on' );
    set( handles.DeleteAllButton, 'Enable', 'on' );
    set( handles.SegCancel, 'Enable', 'on' );
    set( handles.PlotSegments, 'Enable', 'on' );
    set( handles.LoadFile, 'Enable', 'off' );
    set( handles.LoadNext, 'Enable', 'off' );
    handles.start_stop_enable = 1;
    set(handles.datacursor,'Enable','on','DisplayStyle','datatip','SnapToDataVertex','off','UpdateFcn',@datacursorfunc);
    fprintf( 'Segment mode on!\n' );
else
    handles.segmentmode = 0;
    set( handles.SegmentButton, 'String', 'Segment Off' );
    set( handles.AutoSegButton, 'Enable', 'off' );
    set( handles.AutoSegmentFile, 'Enable','off');
    set( handles.SegmentLengthEdit, 'Enable', 'off' );
    set( handles.SegmentLengthText, 'Enable', 'off' );
    set( handles.LoadSegments, 'Enable', 'off' );
    set( handles.SaveSegments, 'Enable', 'off' );
    set( handles.SegStartButton, 'Enable', 'off' );
    set( handles.SegEndButton, 'Enable', 'off' );
    set( handles.DeleteSegment, 'Enable', 'off' );
    set( handles.DeleteAllButton, 'Enable', 'off' );
    set( handles.SegCancel, 'Enable', 'off' );
    set( handles.PlotSegments, 'Enable', 'off' );
    set( handles.LoadFile, 'Enable', 'on' );
    set( handles.LoadNext, 'Enable', 'on' );
    set(handles.datacursor,'Enable','off')
    fprintf( 'Segment mode off!\n' );
end
guidata(gcbo,handles);
% --- Executes on button press in SegStartButton.
function SegStartButton_Callback(hObject, eventdata, handles)
set(handles.LoadSegments, 'Enable', 'off');
set(handles.SegStartButton, 'Enable', 'off');
handles.start_stop_enable = 0;
xy=get(handles.segmentLineP,'Xdata');
handles.segment.start=xy(1);
handles.segment.lines=[];
axes(handles.axesP);
set(handles.segmentLineP,'LineWidth',3);
handles.segment.lines(1) = handles.segmentLineP;
handles.segmentLineP = line('Visible','off');
axes(handles.axesS);
set(handles.segmentLineS,'LineWidth',3);
handles.segment.lines(2) = handles.segmentLineS;
handles.segmentLineS = line('Visible','off');
axes(handles.axesW);
set(handles.segmentLineW,'LineWidth',3);
handles.segment.lines(3) = handles.segmentLineW;
handles.segmentLineW = line('Visible','off');
guidata(gcbo,handles);
% --- Executes on button press in SegEndButton.
function SegEndButton_Callback(hObject, eventdata, handles)
set(handles.SegEndButton, 'Enable', 'off');
handles.start_stop_enable = 1;
xy=get(handles.segmentLineP,'Xdata');
handles.segment.end=xy(1);
handles.segment=draw_all_x(handles, handles.segment);
handles.segments = [handles.segments handles.segment];
guidata(gcbo,handles);
function out=draw_all_x(handles, segment)
segment=draw_x(handles.axesP, segment);
segment=draw_x(handles.axesS, segment);
segment=draw_x(handles.axesW, segment);
out=segment;
function out=draw_x(theaxes, segment)
axes(theaxes);
ylim = get(theaxes,'YLim');
segment.lines = [segment.lines line('Xdata',[segment.start segment.start],'Ydata',ylim,'LineWidth',3)];
segment.lines = [segment.lines line('Xdata',[segment.end segment.end],'Ydata',ylim,'LineWidth',3)];
segment.lines = [segment.lines line('Xdata',[segment.start segment.end],'Ydata',ylim,'LineWidth',3)];
segment.lines = [segment.lines line('Xdata',[segment.start segment.end],'Ydata',[ylim(2) ylim(1)],'LineWidth',3)];
out=segment;
% --- Executes on button press in JumpBack.
function JumpBack_Callback(hObject, eventdata, handles)
Jump_shared(hObject, eventdata, handles, -1)
% --- Executes on button press in Jump.
function Jump_Callback(hObject, eventdata, handles)
Jump_shared(hObject, eventdata, handles, 1)
function Jump_shared(hObject, eventdata, handles, jump_dir)
Tim=eval(get(handles.DisplayWindow,'String'));
tDuration = str2num(get(handles.Duration,'String'));
maxTslider = (tDuration - Tim)/tDuration;
NT=min(round(Tim*handles.Fs),length(handles.ts));
Tslider=get(handles.slider1,'Value');
Tslider = Tslider + jump_dir * Tim * handles.Fs / length(handles.ts);
if Tim > tDuration
    set(handles.DisplayWindow,'String',num2str(tDuration));
    Tslider = 0;
end
if jump_dir == 1 % jumping forward
    if Tslider > maxTslider
        Tslider = maxTslider;
    end
end
if jump_dir == -1 % jumping backwards
    if Tslider < 0
        Tslider = 0
    end
end
% if Tslider > 1
%     Tslider = (length(handles.ts) - NT) / length(handles.ts);
% end
% if Tslider < 0
%     Tslider = 0
% end
set(handles.slider1,'Value',Tslider);
guidata(gcbo,handles);
Plot_Callback(hObject, eventdata, handles)
function LoadNext_Callback(hObject, eventdata, handles)
% Get filename, extension.  Look for next file with same extension, no seg
% file associated
exclude_name = [handles.filename, get(handles.ExcludeExt,'String')];
if not(exist(exclude_name))
     fid=fopen( exclude_name, 'w' );
     fclose( fid);
end
[path] = cell2mat(regexp(handles.filename, '^.*\', 'match'));
[extension] = cell2mat(regexp(handles.filename, '\w+$', 'match'));
dirlist = dir([path '*' extension]);
ndir = length(dirlist);
n = 1;
while n <= ndir
    file = dirlist(n).name;
    if not(exist([path file get(handles.ExcludeExt,'String')]))
        break;
    end
       n = n + 1;
end
if n <= ndir
    set( handles.FileNameString, 'String',file);
    handles.filename = [path file];
    guidata(gcbo,handles);
    handles = loadfile(hObject, eventdata, handles);
else
    error('No more files found matching desired pattern');
end
% --- Executes on button press in Precompute.
function Precompute_Callback(hObject, eventdata, handles)
% handles = guidata(gcbo);
toggled = get(hObject, 'Value');
if toggled
    % Disable spectra configuration parameters
%     set(handles.DisplayWindow, 'Enable', 'off');
    set(handles.WinSize, 'Enable', 'off');
    set(handles.StepSize, 'Enable', 'off');
    set(handles.TW, 'Enable', 'off');
    set(handles.MinFreq, 'Enable', 'off');
    set(handles.MaxFreq, 'Enable', 'off');
    set(handles.SpectrumType, 'Enable', 'off');
%     set(handles.AmpThresh, 'Enable', 'off');
%     set(handles.TDerThresh, 'Enable', 'off');
    set(handles.LoadNext, 'Enable','off');
%    set(handles.LoadFile, 'Enable','off');
    valueTslider = get(handles.slider1,'Value');
    set(handles.slider1,'Value',0);
    strDuration = get(handles.Duration,'String');
    strWindow = get(handles.DisplayWindow,'String');
    handles.firsttime = 1; % indicates that the spectra need to be calculated
    if str2num(strDuration) > handles.maxspec_t
        strDuration = num2str(handles.maxspec_t);
    end
    set(handles.DisplayWindow,'String',strDuration);
    Plot_Callback(handles.Plot, eventdata, handles);
    handles = guidata(hObject);
    handles.firsttime = 0;
    handles.precomputed_spec = 1;
    set(handles.DisplayWindow,'String',strWindow);
    set(handles.slider1,'Value',valueTslider);
    Plot_Callback(handles.Plot, eventdata, handles);
    handles = guidata(hObject);
1000     handles.precomputed_spec = 1;
1001 else
1002   handles.precomputed_spec = 0;
1003
1004
1005   % Enable spectra configuration parameters
1006
1007   handles.S = []; % release memory
1008   handles.t = [];
1009   handles.f = [];
1010
1011   set(handles.WinSize, 'Enable', 'on');
1012     set(handles.StepSize, 'Enable', 'on');
1013     set(handles.TW, 'Enable', 'on');
1014     set(handles.MinFreq, 'Enable', 'on');
1015     set(handles.MaxFreq, 'Enable', 'on');
1016     set(handles.SpectrumType, 'Enable', 'on');
1017 %     set(handles.AmpThresh, 'Enable', 'on');
1018     set(handles.TDerThresh, 'Enable', 'on');
1019     set(handles.LoadNext, 'Enable','on');
1020     set(handles.LoadFile, 'Enable','on');
1021
1022 end
1023
1024 guidata(hObject,handles);
1025
1026 function Precompute_CreateFcn(hObject, eventdata, handles)
1027
1028 function Path_Callback(hObject, eventdata, handles)
1029 path=get(hObject,'String')
1030
1031
1032 function Path_CreateFcn(hObject, eventdata, handles)
1033 set(hObject,'String',pwd);
1034 if ispc
1035     set(hObject,'BackgroundColor','white');
1036 else
1037     set(hObject,'BackgroundColor',get(0,'defaultUicontrolBackgroundColor'));
1038 end
1039
1040 function Extensions_Callback(hObject, eventdata, handles)
1041
1042 function Extensions_CreateFcn(hObject, eventdata, handles)
1043 set(hObject,'String','wav');
1044 if ispc
1045     set(hObject,'BackgroundColor','white');
1046 else
1047     set(hObject,'BackgroundColor',get(0,'defaultUicontrolBackgroundColor'));
1048 end
1049
1050 function Duration_CreateFcn(hObject, eventdata, handles)
1051 if ispc
1052     set(hObject,'BackgroundColor','white');
1053 else
1054     set(hObject,'BackgroundColor',get(0,'defaultUicontrolBackgroundColor'));
1055 end
1056
1057 function LoadSegments_Callback(hObject, eventdata, handles)
1058
1059 handles = load_segment(handles, [handles.filename '.seg.txt']);
1060 set(handles.LoadSegments, 'Enable', 'off');
1061 handles = draw_segments(handles);
1062 guidata(gcbo,handles);
1063
1064 function handles=load_segment(handles,filename)
1065 fid=fopen(filename, 'r');
1066 segments = [];
1067 scanned=fscanf(fid, '%g %g',[2 inf]);
1068 n = 1;
1069
1070 while n <= size(scanned, 2)
1071     segment.start = scanned(1,n);
1072     segment.end = scanned(2,n);
1073     segment.lines = [];
1074     segments = [ segments segment ];
1075     n = n + 1;
1076 end
1077
1078 handles.allsegments = segments; % all segments holds all segments for the file
1079 handles.segments = filtersegments(handles,handles.allsegments); % get segments for the current chunk
1080 handles.loadedsegment = 1; % indicates segments have been filtered
1081
1082 guidata(gcf,handles);
1083
1084
1085 function filteredsegments = filtersegments(handles,segments)
1086 % Returns segments which are in the current defined view. Returns segments
1087 % which are not cut off.
1088
1089 realstart = handles.markerstart / handles.Fs;
1090 realend = handles.markerend / handles.Fs;
1091
1092 filteredsegments = [];
1093
1094 for i = 1:length(segments) % no garuantee segments are in the same order
1095     if (segments(i).start >= realstart) && (segments(i).end <= realend)
1096         filteredsegments = [filteredsegments segments(i)];
1097     end
1098 end
1099
1100 for i=1:length(filteredsegments)
1101     filteredsegments(i).start =  filteredsegments(i).start - realstart;
1102     filteredsegments(i).end =  filteredsegments(i).end - realstart;
1103 end
1104
1105 function ExcludeExt_Callback(hObject, eventdata, handles)
1106
1107 % Hints: get(hObject,'String') returns contents of ExcludeExt as text
1108 %        str2double(get(hObject,'String')) returns contents of ExcludeExt as a double
1109
1110 function ExcludeExt_CreateFcn(hObject, eventdata, handles)
1111
1112 if ispc
1113     set(hObject,'BackgroundColor','white');
1114 else
1115     set(hObject,'BackgroundColor',get(0,'defaultUicontrolBackgroundColor'));
1116 end
1117
1118
1119 function DeleteSegment_Callback(hObject, eventdata, handles)
1120
1121
1122    pos=get(handles.segmentLineP,'Xdata');
1123     n = 1;
1124     while n <= length(handles.segments)
1125         if pos(1) >= handles.segments(n).start && pos(1) <= handles.segments(n).end
1126             handles=delete_segment(handles, n);
1127         else
1128            n = n + 1;
1129         end
1130     end
1131     drawnow;
1132 guidata(gcbo,handles);
1133
1134 function handles=delete_segment(handles, n)
1135             nl = 1;
1136             while nl <= length(handles.segments(n).lines)
1137                 set(handles.segments(n).lines(nl), 'Visible', 'off');
1138                 nl = nl + 1;
1139             end
1140             handles.segments(n) = [];
1141             fprintf('deleted!\n');
1142
1143 function SaveSegments_Callback(hObject, eventdata, handles)
1144
1145 % For the currently defined segments append to the segment list
1146
1147 handles = savesegments2mem(handles);
1148
1149 segment_file = fopen([handles.filename '.seg.txt'], 'wt');
1150 n = 1;
1151 while n <= size(handles.allsegments, 2)
1152     fprintf(segment_file, '%f %f\n', handles.allsegments(n).start, handles.allsegments(n).end);
1153     n = n + 1;
1154 end
1155 fclose(segment_file);
1156 set(handles.SegmentButton, 'Enable', 'on');
1157 guidata(gcbo,handles);
1158
1159 function handles=savesegments2mem(handles)
1160 % Updates the handles allsegments in memory
1161
1162 % first remove in all segments all segments which are in the current chunk
1163
1164 oldsegments = [];
1165
1166 realstart = handles.markerstart / handles.Fs; % readjust time
1167 realend = handles.markerend / handles.Fs; % readjust time
1168
1169 for i = 1:length(handles.allsegments)
1170     if not((handles.allsegments(i).start) >= realstart && (handles.allsegments(i).end <= realend))
1171         oldsegments = [oldsegments handles.allsegments(i)];
1172     end
1173 end
1174
1175 % now put in the new segments
1176
1177 newsegments = [];
1178
1179 for i = 1:length(handles.segments)
1180     segment = handles.segments(i);
1181     segment.start = segment.start + realstart;
1182     segment.end = segment.end + realstart;
1183     newsegments = [newsegments segment];
1184 end
1185
1186 handles.allsegments = [oldsegments newsegments];
1187
1188 function SegCancel_Callback(hObject, eventdata, handles)
1189 set(handles.SegmentButton, 'Enable', 'on');
1190 guidata(gcbo,handles);
1191
1192
1193 function PlotSegments_Callback(hObject, eventdata, handles)
1194
1195 % Load Segments in directory
1196
1197 [path] = cell2mat(regexp(handles.filename, '^.*\', 'match'));
1198 [extension] = cell2mat(regexp(handles.filename, '\w+$', 'match'));
1199
1200 path=get(handles.Path,'String');
1201 extension=get(handles.Extensions,'String');
1202 dirlist = dir([path '\*' extension '.seg.txt']);
1203 ndir = length(dirlist);
1204 n = 1;
1205 all_segments = [];
1206 while n <= ndir
1207     file = dirlist(n).name;
1208     segments = load_segment([path '\' file]);
1209     all_segments = [all_segments segments];
1210     n = n + 1;
1211 end
1212
1213 % Plot info
1214 if length(all_segments) > 2
1215
1216     figure();
1217     axes();
1218     nbin= max(length([all_segments.end])/5,10);
1219     syllable_lengths=[all_segments.end]-[all_segments.start];
1220     hi=hist(syllable_lengths ,nbin);
1221     tl=min(syllable_lengths);
1222     th=max(syllable_lengths);
1223     times=tl:((th-tl)/(nbin-1)):th;
1224     plot(times,hi);
1225     xlabel('Segment Length (s)');
1226     ylabel('N');
1227     title(['All segments in ' path]);
1228 else
1229     error('too few segments to plot');
1230 end
1231 guidata(gcbo,handles);
1232
1233
1234
1235 function AutoSegButton_Callback(hObject, eventdata, handles)
1236
1237     n = 1;
1238     segments = [];
1239     segment.start = 0;
1240     segment.end = 0;
1241     segment.lines = [];
1242     minlen = eval(get(handles.SegmentLengthEdit, 'String'));
1243     while n < length(handles.times)
1244
1245        if (handles.transition(n) > 0)
1246            segment.start = handles.times(n);
1247        end
1248        if (handles.transition(n) < 0)
1249            segment.end = handles.times(n);
1250        end
1251        if (segment.start > 0) && (segment.end) > 0 && (segment.end - segment.start) > minlen
1252            segments = [ segments segment ];
1253            segment.start = 0;
1254             segment.end = 0;
1255        end
1256        n = n + 1;
1257     end
1258
1259     handles.segments = [handles.segments segments];
1260     handles = draw_segments(handles);
1261     guidata(gcbo,handles);
1262
1263 function DeleteAllButton_Callback(hObject, eventdata, handles)
1264
1265 while length(handles.segments)
1266     handles = delete_segment(handles, 1);
1267 end
1268 guidata(gcf,handles);
1269
1270
1271 % --- Executes on button press in PlotAllButton.
1272 function PlotAllButton_Callback(hObject, eventdata, handles)
1273 % hObject    handle to PlotAllButton (see GCBO)
1274 % eventdata  reserved - to be defined in a future version of MATLAB
1275 % handles    structure with handles and user data (see GUIDATA)
1276
1277 set(handles.slider1,'Value',0);
1278
1279 strDuration = get(handles.Duration,'String');
1280
1281 if str2num(strDuration) > handles.maxspec_t
1282     strDuration = num2str(handles.maxspec_t);
1283 end
1284
1285
1286 set(handles.DisplayWindow,'String',strDuration);
1287 Plot_Callback(hObject, eventdata, handles);
1288
1289
1290 % --- Executes on button press in PreviousChunk.
1291 function PreviousChunk_Callback(hObject, eventdata, handles)
1292 % hObject    handle to PreviousChunk (see GCBO)
1293 % eventdata  reserved - to be defined in a future version of MATLAB
1294 % handles    structure with handles and user data (see GUIDATA)
1295
1296 % [handles.markerstart handles.markerend]
1297 handles = savesegments2mem(handles);
1298 handles = loadfile(hObject, eventdata, handles,[handles.markerstart-handles.maxwavsize-1,handles.markerstart-1]);
1299 % [handles.markerstart handles.markerend]
1300 ;
1301 guidata(gcf,handles);
1302
1303 % --- Executes on button press in NextChunk.
1304 function NextChunk_Callback(hObject, eventdata, handles)
1305 % hObject    handle to NextChunk (see GCBO)
1306 % eventdata  reserved - to be defined in a future version of MATLAB
1307 % handles    structure with handles and user data (see GUIDATA)
1308
1309 handles = savesegments2mem(handles);
1310 handles = loadfile(hObject, eventdata, handles, [handles.markerend+1,handles.markerend+1+handles.maxwavsize]);
1311 guidata(gcf,handles);
1312
1313 % --- Executes on button press in AutoSegmentFile.
1314 function AutoSegmentFile_Callback(hObject, eventdata, handles)
1315 % hObject    handle to AutoSegmentFile (see GCBO)
1316 % eventdata  reserved - to be defined in a future version of MATLAB
1317 % handles    structure with handles and user data (see GUIDATA)
1318
1319 while (handles.markerend < handles.wavsize)
1320
1321 PlotAllButton_Callback(hObject, eventdata, handles);
1322 handles = guidata(gcbo);
1323 AutoSegButton_Callback(hObject, eventdata, handles);
1324 handles = guidata(gcbo);
1325 NextChunk_Callback(hObject, eventdata, handles);
1326 handles = guidata(gcbo);
1327
1328 end
1329
1330
1331 PlotAllButton_Callback(hObject, eventdata, handles);
1332 handles = guidata(gcbo);
1333 AutoSegButton_Callback(hObject, eventdata, handles);
1334 handles = guidata(gcbo);
1335 guidata(gcbo,handles);
1336
1337
1338 function MaxSegLength_Callback(hObject, eventdata, handles)
1339 % hObject    handle to MaxSegLength (see GCBO)
1340 % eventdata  reserved - to be defined in a future version of MATLAB
1341 % handles    structure with handles and user data (see GUIDATA)
1342
1343 % Hints: get(hObject,'String') returns contents of MaxSegLength as text
1344 %        str2double(get(hObject,'String')) returns contents of MaxSegLength as a double
1345
1346
1347 % --- Executes during object creation, after setting all properties.
1348 function MaxSegLength_CreateFcn(hObject, eventdata, handles)
1349 % hObject    handle to MaxSegLength (see GCBO)
1350 % eventdata  reserved - to be defined in a future version of MATLAB
1351 % handles    empty - handles not created until after all CreateFcns called
1352
1353 % Hint: edit controls usually have a white background on Windows.
1354 %       See ISPC and COMPUTER.
1355 if ispc
1356     set(hObject,'BackgroundColor','white');
1357 else
1358     set(hObject,'BackgroundColor',get(0,'defaultUicontrolBackgroundColor'));
1359 end
1360
1361 function MaximumWavSize_Callback(hObject, eventdata, handles)
1362 % hObject    handle to MaximumWavSize (see GCBO)
1363 % eventdata  reserved - to be defined in a future version of MATLAB
1364 % handles    structure with handles and user data (see GUIDATA)
1365
1366 % Hints: get(hObject,'String') returns contents of MaximumWavSize as text
1367 %        str2double(get(hObject,'String')) returns contents of MaximumWavSize as a double
1368
1369
1370 % --- Executes during object creation, after setting all properties.
1371 function MaximumWavSize_CreateFcn(hObject, eventdata, handles)
1372 % hObject    handle to MaximumWavSize (see GCBO)
1373 % eventdata  reserved - to be defined in a future version of MATLAB
1374 % handles    empty - handles not created until after all CreateFcns called
1375
1376 % Hint: edit controls usually have a white background on Windows.
1377 %       See ISPC and COMPUTER.
1378 if ispc
1379     set(hObject,'BackgroundColor','white');
1380 else
1381     set(hObject,'BackgroundColor',get(0,'defaultUicontrolBackgroundColor'));
1382 end
1383
1384 % --- Executes on button press in SeekButton.
1385 function SeekButton_Callback(hObject, eventdata, handles)
1386 % hObject    handle to SeekButton (see GCBO)
1387 % eventdata  reserved - to be defined in a future version of MATLAB
1388 % handles    structure with handles and user data (see GUIDATA)
1389
1390 % Seek anywhere in a long file
1391
1392 handles = savesegments2mem(handles);
1393
1394 try
1395     timetoseek = str2num(get(handles.SeektoEdit,'String'));
1396 catch
1397     timetoseek = 0;
1398     set(handles.SeektoEdit,'String','0');
1399 end
1400
1401 if timetoseek < 0
1402     timetoseek = 0;
1403     set(handles.SeektoEdit,'String','0');
1404 end
1405
1406 timetoseek = round(timetoseek * handles.Fs);
1407
1408 if timetoseek >= handles.wavsize
1409     timetoseek = timetoseek - handles.maxwavsize;
1410 end
1411
1412 timetoseek = timetoseek  + 1;
1413 timetoseekend = timetoseek + handles.maxwavsize;
1414
1415 if timetoseekend > handles.wavsize
1416     timetoseekend = handles.wavsize;
1417 end
1418
1419 oldstate = handles.dontcutsegments;
1420 handles.dontcutsegments = 0;
1421 handles = loadfile(hObject,eventdata,handles,[timetoseek timetoseekend]);
1422 handles.dontcutsegments = oldstate;
1423
1424 guidata(gcbo,handles);
1425
1426 function SeektoEdit_Callback(hObject, eventdata, handles)
1427 % hObject    handle to SeektoEdit (see GCBO)
1428 % eventdata  reserved - to be defined in a future version of MATLAB
1429 % handles    structure with handles and user data (see GUIDATA)
1430
1431 % Hints: get(hObject,'String') returns contents of SeektoEdit as text
1432 %        str2double(get(hObject,'String')) returns contents of SeektoEdit as a double
1433
1434
1435 % --- Executes during object creation, after setting all properties.
1436 function SeektoEdit_CreateFcn(hObject, eventdata, handles)
1437 % hObject    handle to SeektoEdit (see GCBO)
1438 % eventdata  reserved - to be defined in a future version of MATLAB
1439 % handles    empty - handles not created until after all CreateFcns called
1440
1441 % Hint: edit controls usually have a white background on Windows.
1442 %       See ISPC and COMPUTER.
1443 if ispc
1444     set(hObject,'BackgroundColor','white');
1445 else
1446     set(hObject,'BackgroundColor',get(0,'defaultUicontrolBackgroundColor'));
1447 end
1448
1449
1450
1451
1452
1453 function RealDuration_Callback(hObject, eventdata, handles)
1454 % hObject    handle to RealDuration (see GCBO)
1455 % eventdata  reserved - to be defined in a future version of MATLAB
1456 % handles    structure with handles and user data (see GUIDATA)
1457
1458 % Hints: get(hObject,'String') returns contents of RealDuration as text
1459 %        str2double(get(hObject,'String')) returns contents of RealDuration as a double
1460
1461
1462 % --- Executes during object creation, after setting all properties.
1463 function RealDuration_CreateFcn(hObject, eventdata, handles)
1464 % hObject    handle to RealDuration (see GCBO)
1465 % eventdata  reserved - to be defined in a future version of MATLAB
1466 % handles    empty - handles not created until after all CreateFcns called
1467
1468 % Hint: edit controls usually have a white background on Windows.
1469 %       See ISPC and COMPUTER.
1470 if ispc
1471     set(hObject,'BackgroundColor','white');
1472 else
1473     set(hObject,'BackgroundColor',get(0,'defaultUicontrolBackgroundColor'));
1474 end
1475
1476
1477
1478
1479 % --- Executes on selection change in AutoMethodPopupMenu.
1480 function AutoMethodPopupMenu_Callback(hObject, eventdata, handles)
1481 % hObject    handle to AutoMethodPopupMenu (see GCBO)
1482 % eventdata  reserved - to be defined in a future version of MATLAB
1483 % handles    structure with handles and user data (see GUIDATA)
1484
1485 % Hints: contents = get(hObject,'String') returns AutoMethodPopupMenu contents as cell array
1486 %        contents{get(hObject,'Value')} returns selected item from AutoMethodPopupMenu
1487 contents = get(hObject,'String');
1488 method = contents{get(hObject,'Value')}
1489
1490 if strcmp(method,'Summed intensity')
1491     handles.automethod = 'threshold';
1492     set(handles.AmpThresh,'Visible','on');
1493     set(handles.RatioThresh,'Visible','off');
1494 elseif strcmp(method,'Ratio')
1495     handles.automethod = 'ratiof';
1496     set(handles.AmpThresh,'Visible','off');
1497     set(handles.RatioThresh,'Visible','on');
1498 end
1499
1500 guidata(gcbo,handles);
1501
1502 % --- Executes during object creation, after setting all properties.
1503 function AutoMethodPopupMenu_CreateFcn(hObject, eventdata, handles)
1504 % hObject    handle to AutoMethodPopupMenu (see GCBO)
1505 % eventdata  reserved - to be defined in a future version of MATLAB
1506 % handles    empty - handles not created until after all CreateFcns called
1507
1508 % Hint: popupmenu controls usually have a white background on Windows.
1509 %       See ISPC and COMPUTER.
1510 if ispc
1511     set(hObject,'BackgroundColor','white');
1512 else
1513     set(hObject,'BackgroundColor',get(0,'defaultUicontrolBackgroundColor'));
1514 end
1515
1516
1517
1518 function RatioThresh_Callback(hObject, eventdata, handles)
1519 % hObject    handle to RatioThresh (see GCBO)
1520 % eventdata  reserved - to be defined in a future version of MATLAB
1521 % handles    structure with handles and user data (see GUIDATA)
1522
1523 % Hints: get(hObject,'String') returns contents of RatioThresh as text
1524 %        str2double(get(hObject,'String')) returns contents of RatioThresh as a double
1525
1526
1527 % --- Executes during object creation, after setting all properties.
1528 function RatioThresh_CreateFcn(hObject, eventdata, handles)
1529 % hObject    handle to RatioThresh (see GCBO)
1530 % eventdata  reserved - to be defined in a future version of MATLAB
1531 % handles    empty - handles not created until after all CreateFcns called
1532
1533 % Hint: edit controls usually have a white background on Windows.
1534 %       See ISPC and COMPUTER.
1535 if ispc
1536     set(hObject,'BackgroundColor','white');
1537 else
1538     set(hObject,'BackgroundColor',get(0,'defaultUicontrolBackgroundColor'));
1539 end
1540
1541
1542
1543 function RatioLower_Callback(hObject, eventdata, handles)
1544 % hObject    handle to RatioLower (see GCBO)
1545 % eventdata  reserved - to be defined in a future version of MATLAB
1546 % handles    structure with handles and user data (see GUIDATA)
1547
1548 % Hints: get(hObject,'String') returns contents of RatioLower as text
1549 %        str2double(get(hObject,'String')) returns contents of RatioLower as a double
1550
1551
1552 % --- Executes during object creation, after setting all properties.
1553 function RatioLower_CreateFcn(hObject, eventdata, handles)
1554 % hObject    handle to RatioLower (see GCBO)
1555 % eventdata  reserved - to be defined in a future version of MATLAB
1556 % handles    empty - handles not created until after all CreateFcns called
1557
1558 % Hint: edit controls usually have a white background on Windows.
1559 %       See ISPC and COMPUTER.
1560 if ispc
1561     set(hObject,'BackgroundColor','white');
1562 else
1563     set(hObject,'BackgroundColor',get(0,'defaultUicontrolBackgroundColor'));
1564 end
1565
1566
1567
1568 function RatioUpper_Callback(hObject, eventdata, handles)
1569 % hObject    handle to RatioUpper (see GCBO)
1570 % eventdata  reserved - to be defined in a future version of MATLAB
1571 % handles    structure with handles and user data (see GUIDATA)
1572
1573 % Hints: get(hObject,'String') returns contents of RatioUpper as text
1574 %        str2double(get(hObject,'String')) returns contents of RatioUpper as a double
1575
1576
1577 % --- Executes during object creation, after setting all properties.
1578 function RatioUpper_CreateFcn(hObject, eventdata, handles)
1579 % hObject    handle to RatioUpper (see GCBO)
1580 % eventdata  reserved - to be defined in a future version of MATLAB
1581 % handles    empty - handles not created until after all CreateFcns called
1582
1583 % Hint: edit controls usually have a white background on Windows.
1584 %       See ISPC and COMPUTER.
1585 if ispc
1586     set(hObject,'BackgroundColor','white');
1587 else
1588     set(hObject,'BackgroundColor',get(0,'defaultUicontrolBackgroundColor'));
1589 end
1590
1591
1592 % --- Executes on button press in OptionsDisplay.
1593 function OptionsDisplay_Callback(hObject, eventdata, handles)
1594 % hObject    handle to OptionsDisplay (see GCBO)
1595 % eventdata  reserved - to be defined in a future version of MATLAB
1596 % handles    structure with handles and user data (see GUIDATA)
1597
1598 % Hint: get(hObject,'Value') returns toggle state of OptionsDisplay
1599
1600 % positionP = get(handles.OptionsUiPanel,'Position');
1601 % positionF = get(gcf,'Position');
1602
1603 state = get(hObject,'Value');
1604
1605 if state
1606     set(handles.OptionsUiPanel,'Visible','on');
1607 %     positionF(3) = positionF(3) + positionP(3);
1608 else
1609     set(handles.OptionsUiPanel,'Visible','off');
1610 %     positionF(3) = positionF(3) - positionP(3);
1611 end
1612
1613 %  set(gcf,'Position',positionF); % untested
1614
1615 guidata(gcbo,handles)
1616
1617
1618
1619 function Duration_Callback(hObject, eventdata, handles)
1620 % hObject    handle to Duration (see GCBO)
1621 % eventdata  reserved - to be defined in a future version of MATLAB
1622 % handles    structure with handles and user data (see GUIDATA)
1623
1624 % Hints: get(hObject,'String') returns contents of Duration as text
1625 %        str2double(get(hObject,'String')) returns contents of Duration as a double
1626
1627
1628
1629
1630
1631 function SmoothFactor_Callback(hObject, eventdata, handles)
1632 % hObject    handle to SmoothFactor (see GCBO)
1633 % eventdata  reserved - to be defined in a future version of MATLAB
1634 % handles    structure with handles and user data (see GUIDATA)
1635
1636 % Hints: get(hObject,'String') returns contents of SmoothFactor as text
1637 %        str2double(get(hObject,'String')) returns contents of SmoothFactor as a double
1638
1639
1640 % --- Executes during object creation, after setting all properties.
1641 function SmoothFactor_CreateFcn(hObject, eventdata, handles)
1642 % hObject    handle to SmoothFactor (see GCBO)
1643 % eventdata  reserved - to be defined in a future version of MATLAB
1644 % handles    empty - handles not created until after all CreateFcns called
1645
1646 % Hint: edit controls usually have a white background on Windows.
1647 %       See ISPC and COMPUTER.
1648 if ispc
1649     set(hObject,'BackgroundColor','white');
1650 else
1651     set(hObject,'BackgroundColor',get(0,'defaultUicontrolBackgroundColor'));
1652 end
1653
1654
1655
1656
1657
1658 function channel_Callback(hObject, eventdata, handles)
1659 % hObject    handle to channel (see GCBO)
1660 % eventdata  reserved - to be defined in a future version of MATLAB
1661 % handles    structure with handles and user data (see GUIDATA)
1662
1663 % Hints: get(hObject,'String') returns contents of channel as text
1664 %        str2double(get(hObject,'String')) returns contents of channel as a double
1665
1666
1667
1668 % --- Executes during object creation, after setting all properties.
1669 function channel_CreateFcn(hObject, eventdata, handles)
1670 % hObject    handle to channel (see GCBO)
1671 % eventdata  reserved - to be defined in a future version of MATLAB
1672 % handles    empty - handles not created until after all CreateFcns called
1673
1674 % Hint: edit controls usually have a white background on Windows.
1675 %       See ISPC and COMPUTER.
1676 if ispc && isequal(get(hObject,'BackgroundColor'), get(0,'defaultUicontrolBackgroundColor'))
1677     set(hObject,'BackgroundColor','white');
1678 end
1679
1680