#!/bin/bash

wget https://buzsakilab.nyumc.org/datasets/TingleyD/DT9/20170505_396um_0um_merge/20170505_396um_0um_merge.lfp
wget https://buzsakilab.nyumc.org/datasets/TingleyD/DT9/20170505_396um_0um_merge.CA1Ripples.events.mat
wget https://buzsakilab.nyumc.org/datasets/TingleyD/DT9/20170505_396um_0um_merge/20170505_396um_0um_merge.firingMaps.cellinfo.mat
