Description of defaultVideoIOPlugin
defaultVideoIOPlugin
PURPOSE
pluginName = defaultVideoIOPlugin
SYNOPSIS
function pluginName = defaultVideoIOPlugin
DESCRIPTION
pluginName = defaultVideoIOPlugin
  Returns the name of the default videoIO (videoReader/videoWriter) plugin.
  The videoReader and videoWriter constructors will use the returned plugin if
  none is specified.
 SEE ALSO:
   buildVideoIO
   videoReader
   videoWriter
Copyright (c) 2007 Gerald Dalley
See "MIT.txt" in the installation directory for licensing details (especially
when using this library on GNU/Linux).
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
videoReader videoReader class constructor
videoWriter videoWriter class constructor
videoReader videoReader class constructor
videoWriter videoWriter class constructor
videoReader videoReader class constructor
videoWriter videoWriter class constructor
SOURCE CODE
function pluginName = defaultVideoIOPlugin
%pluginName = defaultVideoIOPlugin
%  Returns the name of the default videoIO (videoReader/videoWriter) plugin.
%  The videoReader and videoWriter constructors will use the returned plugin if
%  none is specified.
%
% SEE ALSO:
%   buildVideoIO
%   videoReader
%   videoWriter
%
%Copyright (c) 2007 Gerald Dalley
%See "MIT.txt" in the installation directory for licensing details (especially
%when using this library on GNU/Linux).
if ispc
  pluginName = 'DirectShow';
else
  pluginName = 'ffmpegPopen2';
end