Description of minmaxsptimes
minmaxsptimes
PURPOSE
Find the minimum and maximum of the spike times in each channel
SYNOPSIS
function [mintime, maxtime]=minmaxsptimes(data)
DESCRIPTION
 Find the minimum and maximum of the spike times in each channel
 Usage: [mintime, maxtime]=minmaxsptimes(data)
 Input:
 data  (spike times as a structural array of multiple dimensions e.g. channels; channels x trials;
        can also accept a 1d matrix of spike times)
 Output:
 mintime       (minimum of the spike time across channels)
 maxtime       (maximum of the spike time across channels)
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
CrossSpecMatpt
coherencypt Multi-taper coherency - point process times
coherencysegpt Multi-taper coherency computed by segmenting two univariate point processes into chunks
cohgrampt Multi-taper time-frequency coherence - two point processes given as times
cohmatrixpt Multi-taper coherency matrix - point process times
mtdspecgrampt Multi-taper derivative time-frequency spectrum - point process times
mtdspectrumpt Multi-taper spectral derivative - point process times
mtspecgrampt Multi-taper time-frequency spectrum - point process times
mtspectrumpt Multi-taper spectrum - point process times
mtspectrumsegpt Multi-taper segmented spectrum for a univariate binned point process
SOURCE CODE
function [mintime, maxtime]=minmaxsptimes(data)
% Find the minimum and maximum of the spike times in each channel
% Usage: [mintime, maxtime]=minmaxsptimes(data)
% Input:
% data  (spike times as a structural array of multiple dimensions e.g. channels; channels x trials;
%        can also accept a 1d matrix of spike times)
% Output:
% mintime       (minimum of the spike time across channels)
% maxtime       (maximum of the spike time across channels)
%
dtmp='';
if isstruct(data)
   data=reshape(data,numel(data),1);
   C=size(data,1);
   fnames=fieldnames(data);
   mintime=zeros(1,C); maxtime=zeros(1,C);
   for ch=1:C
     eval(['dtmp=data(ch).' fnames{1} ';'])
     if ~isempty(dtmp)
        maxtime(ch)=max(dtmp);
        mintime(ch)=min(dtmp);
     else
        mintime(ch)=NaN;
        maxtime(ch)=NaN;
     end
   end;
   maxtime=max(maxtime); % maximum time
   mintime=min(mintime); % minimum time
else
     dtmp=data;
     if ~isempty(dtmp)
        maxtime=max(dtmp);
        mintime=min(dtmp);
     else
        mintime=NaN;
        maxtime=NaN;
     end
end
if mintime < 0
   error('Minimum spike time is negative');
end