Description of mtspectrumpt
mtspectrumpt
PURPOSE
Multi-taper spectrum - point process times
SYNOPSIS
function [S,f,R,Serr]=mtspectrumpt(data,params,fscorr,t)
DESCRIPTION
 Multi-taper spectrum - point process times
 Usage:
 [S,f,R,Serr]=mtspectrumpt(data,params,fscorr,t)
 Input:
       data        (structure array of spike times with dimension channels/trials;
                   also accepts 1d array of spike times) -- required
       params: structure with fields tapers, pad, Fs, fpass, err, trialave
       - optional
           tapers : precalculated tapers from dpss or in the one of the following
                    forms:
                   (1) A numeric vector [TW K] where TW is the
                       time-bandwidth product and K is the number of
                       tapers to be used (less than or equal to
                       2TW-1).
                   (2) A numeric vector [W T p] where W is the
                       bandwidth, T is the duration of the data and p
                       is an integer such that 2TW-p tapers are used. In
                       this form there is no default i.e. to specify
                       the bandwidth, you have to specify T and p as
                       well. Note that the units of W and T have to be
                       consistent: if W is in Hz, T must be in seconds
                       and vice versa. Note that these units must also
                       be consistent with the units of params.Fs: W can
                       be in Hz if and only if params.Fs is in Hz.
                       The default is to use form 1 with TW=3 and K=5
            pad            (padding factor for the FFT) - optional (can take values -1,0,1,2...).
                    -1 corresponds to no padding, 0 corresponds to padding
                    to the next highest power of 2 etc.
                       e.g. For N = 500, if PAD = -1, we do not pad; if PAD = 0, we pad the FFT
                       to 512 points, if pad=1, we pad to 1024 points etc.
                       Defaults to 0.
           Fs   (sampling frequency) - optional. Default 1.
           fpass    (frequency band to be used in the calculation in the form
                                   [fmin fmax])- optional.
                                   Default all frequencies between 0 and Fs/2
           err  (error calculation [1 p] - Theoretical error bars; [2 p] - Jackknife error bars
                                   [0 p] or 0 - no error bars) - optional. Default 0.
           trialave (average over channels/trials when 1, don't average when 0) - optional. Default 0
       fscorr   (finite size corrections, 0 (don't use finite size corrections) or
                1 (use finite size corrections) - optional
                (available only for spikes). Defaults 0.
       t        (time grid over which the tapers are to be calculated:
                      this argument is useful when calling the spectrum
                      calculation routine from a moving window spectrogram
                      calculation routine). If left empty, the spike times
                      are used to define the grid.
 Output:
       S       (spectrum with dimensions frequency x channels/trials if trialave=0;
               dimension frequency if trialave=1)
       f       (frequencies)
       R       (rate)
       Serr    (error bars) - only if err(1)>=1
CROSS-REFERENCE INFORMATION
This function calls:
change_row_to_column Helper routine to transform 1d arrays into column vectors that are needed
dpsschk Helper function to calculate tapers and, if precalculated tapers are supplied,
getfgrid Helper function that gets the frequency grid associated with a given fft based computation
getparams Helper function to convert structure params to variables used by the
specerr Function to compute lower and upper confidence intervals on the spectrum
minmaxsptimes Find the minimum and maximum of the spike times in each channel
mtfftpt Multi-taper fourier transform for point process given as times
This function is called by:
mtspecgrampt Multi-taper time-frequency spectrum - point process times
mtspectrumtrigpt Multi-taper time-frequency spectrum - point process times
testscript function testscript(pname,direction,movingwin,segave,params,fscorr)
SOURCE CODE
function [S,f,R,Serr]=mtspectrumpt(data,params,fscorr,t)
% Multi-taper spectrum - point process times
%
% Usage:
%
% [S,f,R,Serr]=mtspectrumpt(data,params,fscorr,t)
% Input:
%       data        (structure array of spike times with dimension channels/trials;
%                   also accepts 1d array of spike times) -- required
%       params: structure with fields tapers, pad, Fs, fpass, err, trialave
%       - optional
%           tapers : precalculated tapers from dpss or in the one of the following
%                    forms:
%                   (1) A numeric vector [TW K] where TW is the
%                       time-bandwidth product and K is the number of
%                       tapers to be used (less than or equal to
%                       2TW-1).
%                   (2) A numeric vector [W T p] where W is the
%                       bandwidth, T is the duration of the data and p
%                       is an integer such that 2TW-p tapers are used. In
%                       this form there is no default i.e. to specify
%                       the bandwidth, you have to specify T and p as
%                       well. Note that the units of W and T have to be
%                       consistent: if W is in Hz, T must be in seconds
%                       and vice versa. Note that these units must also
%                       be consistent with the units of params.Fs: W can
%                       be in Hz if and only if params.Fs is in Hz.
%                       The default is to use form 1 with TW=3 and K=5
%
%            pad            (padding factor for the FFT) - optional (can take values -1,0,1,2...).
%                    -1 corresponds to no padding, 0 corresponds to padding
%                    to the next highest power of 2 etc.
%                       e.g. For N = 500, if PAD = -1, we do not pad; if PAD = 0, we pad the FFT
%                       to 512 points, if pad=1, we pad to 1024 points etc.
%                       Defaults to 0.
%           Fs   (sampling frequency) - optional. Default 1.
%           fpass    (frequency band to be used in the calculation in the form
%                                   [fmin fmax])- optional.
%                                   Default all frequencies between 0 and Fs/2
%           err  (error calculation [1 p] - Theoretical error bars; [2 p] - Jackknife error bars
%                                   [0 p] or 0 - no error bars) - optional. Default 0.
%           trialave (average over channels/trials when 1, don't average when 0) - optional. Default 0
%       fscorr   (finite size corrections, 0 (don't use finite size corrections) or
%                1 (use finite size corrections) - optional
%                (available only for spikes). Defaults 0.
%       t        (time grid over which the tapers are to be calculated:
%                      this argument is useful when calling the spectrum
%                      calculation routine from a moving window spectrogram
%                      calculation routine). If left empty, the spike times
%                      are used to define the grid.
% Output:
%       S       (spectrum with dimensions frequency x channels/trials if trialave=0;
%               dimension frequency if trialave=1)
%       f       (frequencies)
%       R       (rate)
%       Serr    (error bars) - only if err(1)>=1
if nargin < 1; error('Need data'); end;
if nargin < 2; params=[]; end;
[tapers,pad,Fs,fpass,err,trialave,params]=getparams(params);
clear params
data=change_row_to_column(data);
if nargout > 3 && err(1)==0; error('cannot compute error bars with err(1)=0; change params and run again'); end;
if nargin < 3 || isempty(fscorr); fscorr=0;end;
if nargin < 4 || isempty(t);
   [mintime,maxtime]=minmaxsptimes(data);
   dt=1/Fs; % sampling time
   t=mintime-dt:dt:maxtime+dt; % time grid for prolates
end;
N=length(t); % number of points in grid for dpss
nfft=max(2^(nextpow2(N)+pad),N); % number of points in fft of prolates
[f,findx]=getfgrid(Fs,nfft,fpass); % get frequency grid for evaluation
tapers=dpsschk(tapers,N,Fs); % check tapers
[J,Msp,Nsp]=mtfftpt(data,tapers,nfft,t,f,findx); % mt fft for point process times
S=squeeze(mean(conj(J).*J,2));
if trialave; S=squeeze(mean(S,2));Msp=mean(Msp);end;
R=Msp*Fs;
if nargout==4;
   if fscorr==1;
      Serr=specerr(S,J,err,trialave,Nsp);
   else
      Serr=specerr(S,J,err,trialave);
   end;
end;