Description of fig1_2
fig1_2
PURPOSE
Local Regression and Likelihood, Figure 1.2.
SYNOPSIS
This is a script file.
DESCRIPTION
 Local Regression and Likelihood, Figure 1.2.
 Spencer's mortality data, 15- and 21-point rules.
 Doesn't use locfit!
CROSS-REFERENCE INFORMATION
This function calls:
spence15 function for Spencer's 15-point graduation rule.
spence21 function for Spencer's 21-point graduation rule.
This function is called by:
runbook
SOURCE CODE
% Local Regression and Likelihood, Figure 1.2.
%
% Spencer's mortality data, 15- and 21-point rules.
% Doesn't use locfit!
load spencer;
figure('Name','fig1_2a: Spencer mortality data');
plot(age,mortality,'o');
title('15-point rule');
xlabel('Age (Years)');
ylabel('Mortality Rate');
hold on;
plot(age,spence15(mortality));
hold off;
figure('Name','fig1_2b: Spencer mortality data');
plot(age,mortality,'o');
xlabel('Age (Years)');
ylabel('Mortality Rate');
title('21-point rule');
hold on;
plot(age,spence21(mortality));
hold off;