Description of fig2_3
fig2_3
PURPOSE
Local Regression and Likelihood, Figure 2.3.
SYNOPSIS
This is a script file.
DESCRIPTION
 Local Regression and Likelihood, Figure 2.3.
 Using different smoothing parameters.
CROSS-REFERENCE INFORMATION
This function calls:
lfplot Plot (for one or two dimensions) a locfit() fit.
locfit Smoothing noisy data using Local Regression and Likelihood.
This function is called by:
runbook
SOURCE CODE
% Local Regression and Likelihood, Figure 2.3.
%
% Using different smoothing parameters.
load ethanol;
alp = [0.2 0.4 0.6 0.8];
f=['a','b','c','d'];
for (i=1:4)
  figure('Name', sprintf( 'figure2_3%c: Changing smoothing parameters', f(i) ) );
  fit = locfit(E,NOx,'alpha',alp(i));
  lfplot(fit);
  title(strcat('a = ',num2str(alp(i))));
end;