Description of fig2_4
fig2_4
PURPOSE
Local Regression and Likelihood, Figure 2.4.
SYNOPSIS
This is a script file.
DESCRIPTION
 Local Regression and Likelihood, Figure 2.4.
 Bivariate Local Regression.
CROSS-REFERENCE INFORMATION
This function calls:
lfplot Plot (for one or two dimensions) a locfit() fit.
locfit Smoothing noisy data using Local Regression and Likelihood.
This function is called by:
runbook
SOURCE CODE
% Local Regression and Likelihood, Figure 2.4.
%
% Bivariate Local Regression.
load ethanol;
alp = [0.25 0.3 0.49 0.59];
lab = {'Local Constant' 'Local Linear' 'Local Quadratic' 'Local Cubic'};
f=['a','b','c','d'];
for (i=1:4)
  figure('Name', sprintf( 'figure2_4%c: Bivariate local regression', f(i) ) );
    fit = locfit(E,NOx,'deg',i-1,'alpha',alp(i));
    lfplot(fit);
    title(lab(i));
end;