Description of fig7_5
fig7_5
PURPOSE
Local Regression and Likelihood, Figure 7.5.
SYNOPSIS
This is a script file.
DESCRIPTION
 Local Regression and Likelihood, Figure 7.5.
 Author: Catherine Loader
CROSS-REFERENCE INFORMATION
This function calls:
lfmarg computes grid margins from a locfit object, used for plotting.
locfit Smoothing noisy data using Local Regression and Likelihood.
predict Interpolate a fit produced by locfit().
This function is called by:
runbook
SOURCE CODE
% Local Regression and Likelihood, Figure 7.5.
%
% Author: Catherine Loader
load border;
fit0 = locfit(day,runs,'cens',no,'family','geom','nn',0.7);
fit1 = locfit(day,runs,'weights',ones(265,1)*0.8,'cens',no,'family','geom','nn',0.7);
xev = lfmarg(fit);
xev = xev{1};
y0 = predict(fit0,xev);
y1 = predict(fit1,xev);
figure('Name','fig7_5');
plot(xev,0.8*exp(y1)-exp(y0));
xlabel('Date');
ylabel('Runs');