Description of fig8_1
fig8_1
PURPOSE
Local Regression and Likelihood, Figure 8.1.
SYNOPSIS
This is a script file.
DESCRIPTION
 Local Regression and Likelihood, Figure 8.1.
 Discrimination/Classification, simple example using
 logistic regression.
 Author: Catherine Loader
 NEED: level=0.5 for contour plot.
CROSS-REFERENCE INFORMATION
This function calls:
fitted Fitted values from a locfit object.
lfplot Plot (for one or two dimensions) a locfit() fit.
locfit Smoothing noisy data using Local Regression and Likelihood.
predict Interpolate a fit produced by locfit().
This function is called by:
runbook
SOURCE CODE
% Local Regression and Likelihood, Figure 8.1.
%
% Discrimination/Classification, simple example using
% logistic regression.
%
% Author: Catherine Loader
%
% NEED: level=0.5 for contour plot.
load cltrain;
fit = locfit([x1 x2],y,'family','binomial','scale',0);
figure('Name','fig8_1: logistic regression');
lfplot(fit,'contour');
hold on;
u = find(y==0);
plot(x1(u),x2(u),'.');
u = find(y==1);
plot(x1(u),x2(u),'.','color','red');
hold off;
py = fitted(fit)>0.5;
disp('Classification table for training data');
tabulate(10*y+py);
load cltest;
py = predict(fit,[x1 x2])>0;
disp('Classification table for test data');
tabulate(10*y+py);