Description of createdatamatc
createdatamatc
PURPOSE
Helper function to create an event triggered matrix from univariate
SYNOPSIS
function data=createdatamatc(data,E,Fs,win)
DESCRIPTION
 Helper function to create an event triggered matrix from univariate
 continuous data
 Usage: data=createdatamatc(data,E,Fs,win)
 Inputs:
 data   (input time series as a column vector) - required
 E      (events to use as triggers) - required
 Fs     (sampling frequency of data) - required
 win    (window around triggers to use data matrix -[winl winr]) - required
          e.g [1 1] uses a window starting 1 * Fs samples before E and
              ending 1*Fs samples after E.
 Note that E, Fs, and win must have consistent units
 Outputs:
 data      (event triggered data)
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
significant-spike-field-coherenceMBL2005
spike-field-coherenceMBL2005
coherencysegc Multi-taper coherency, cross-spectrum and individual spectra with segmenting - continuous process
mtspecgramtrigc Multi-taper event triggered time-frequency spectrum - continuous process
mtspectrum_of_spectrumc Multi-taper segmented, second spectrum (spectrum of the log spectrum) for a continuous process
mtspectrumsegc Multi-taper segmented spectrum for a univariate continuous process
mtspectrumtrigc Multi-taper event triggered time-frequency spectrum - continuous process
coherencysegcpb Multi-taper coherency,cross-spectrum and individual spectra with segmenting
coherencysegcpt Multi-taper coherency,cross-spectrum and individual spectra computed by segmenting
SOURCE CODE
function data=createdatamatc(data,E,Fs,win)
% Helper function to create an event triggered matrix from univariate
% continuous data
% Usage: data=createdatamatc(data,E,Fs,win)
% Inputs:
% data   (input time series as a column vector) - required
% E      (events to use as triggers) - required
% Fs     (sampling frequency of data) - required
% win    (window around triggers to use data matrix -[winl winr]) - required
%          e.g [1 1] uses a window starting 1 * Fs samples before E and
%              ending 1*Fs samples after E.
% Note that E, Fs, and win must have consistent units
%
% Outputs:
% data      (event triggered data)
%
if nargin < 4; error('Need all arguments'); end;
NE=length(E);
nwinl=round(win(1)*Fs);
nwinr=round(win(2)*Fs);
nE=floor(E*Fs)+1;
datatmp=[];
for n=1:NE;
    indx=nE(n)-nwinl:nE(n)+nwinr-1;
    datatmp=[datatmp data(indx)];
end
data=datatmp;