Description of Data
Home > @tsd > Data.m
Data
PURPOSE
Returns Data of a TSD object
SYNOPSIS
function v = Data(tsa, ix)
DESCRIPTION
 Returns Data of a TSD object
      USAGE
      d = Data(tsa)
      d = Data(tsa, alignments)
      Retrieves data from ctsd
      if called with alignment list (timestamps), returns those tsa.Data(ix)
      if called without, returns complete tsa.Data
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
FindPeaks Get peaks in data
cat Concatenation of TSD objects
interp_missing Interpolate missing values in continuously sampled tsd
intervalFun im = intervalFun(tsa, is, func, options) computes mean of tsa data in each of the intervals in isw
intervalMean Computes mean of of data in each of subset of a given interval
peaks Get peaks in data
smooth Smooth a TSD
subset Returns tsd of a subset of input
timeDeriv TimeDerivative of a tsd
triggeredDataMat Returns a event-by-events matrix of Data component triggered on a reference (TODO!)
triggeredMeanData Event-triggered mean of the Data component, triggered on events (TODO)
tsd Constructor of TSD object
SOURCE CODE
function v = Data(tsa, ix)
% Returns Data of a TSD object
%
%      USAGE
%      d = Data(tsa)
%      d = Data(tsa, alignments)
%
%      Retrieves data from ctsd
%      if called with alignment list (timestamps), returns those tsa.Data(ix)
%      if called without, returns complete tsa.Data
% ADR 1998
% version L4.1
% status: PROMOTED
switch nargin
case 2
   f = findAlignment(tsa, ix)
   v = SelectAlongFirstDimension(tsa.data,f);
  case 1
    v = tsa.data;
  otherwise
    error('Unknown number of input arguments');
end