Description of find
Home > @tsd > find.m
find
PURPOSE
Selects points in a TSD object based on conditions
SYNOPSIS
function O = find(tsa, find_string)
DESCRIPTION
  Selects points in a TSD object based on conditions
      USAGE:
      O = find(tsa, find_string)
      INPUTS:
      tsa         - a tsd object
      find_string - a string that represent a condition, in which the data is
              substituted by the symbol 'Td', and the timestamps
              by the symbol 'Tt'
      OUTPUTS:
      O - the resulting tsd object
CROSS-REFERENCE INFORMATION
This function calls:
tsd Constructor of TSD object
This function is called by:
FindPeaks Get peaks in data
classify Breaks a TSD object in many tsds according to the value of data
median_dt Find the median value of inter-event interval
peaks Get peaks in data
threshold Threshold crossings
triggeredDataMat Returns a event-by-events matrix of Data component triggered on a reference (TODO!)
triggeredMeanData Event-triggered mean of the Data component, triggered on events (TODO)
SOURCE CODE
function O = find(tsa, find_string)
%  Selects points in a TSD object based on conditions
%
%      USAGE:
%      O = find(tsa, find_string)
%
%      INPUTS:
%      tsa         - a tsd object
%      find_string - a string that represent a condition, in which the data is
%              substituted by the symbol 'Td', and the timestamps
%              by the symbol 'Tt'
%
%      OUTPUTS:
%      O - the resulting tsd object
% copyright (c) 2004 Francesco P. Battaglia
% This software is released under the GNU GPL
% www.gnu.org/copyleft/gpl.html
  fs = substr(find_string, 'Td', 'tsa.data');
  fs = substr(fs, 'Tt', 'tsa.t');
  ix = eval(['find( ' fs ');']);
  O = tsd(tsa.t(ix), SelectAlongFirstDimension(tsa.data, ix));