Description of plus
Home > @tsd > plus.m
plus
PURPOSE
Overload of the + operator
SYNOPSIS
function s = plus(a,b)
DESCRIPTION
  Overload of the + operator
      USAGE:
      s = plus(a,b)
      the + operaetor is defined to return a tsd with same timestamps and
      data that are the sum of the data. Returns error if timestamps of the
      two object don't coincide. One of the two operands may be a scalar
CROSS-REFERENCE INFORMATION
This function calls:
compatible_ts Tells whether two tsd's have the same timestamps, within relative tolerance
size Return the size of the data component (overoad of the size function)
tsd Constructor of TSD object
This function is called by:
SOURCE CODE
function s = plus(a,b)
%  Overload of the + operator
%
%      USAGE:
%      s = plus(a,b)
%
%      the + operaetor is defined to return a tsd with same timestamps and
%      data that are the sum of the data. Returns error if timestamps of the
%      two object don't coincide. One of the two operands may be a scalar
% copyright (c) 2004 Francesco P. Battaglia
% This software is released under the GNU GPL
% www.gnu.org/copyleft/gpl.html
  if (isa(a, 'tsd') & isa(b, 'tsd'))
    if ~compatible_ts(a, b)
      error('Timestamps mismatch')
    end
    s = tsd(a.t, a.data+b.data);
  elseif (isa(a, 'tsd') & isa(b, 'numeric'))
    if(prod(size(b))) ~= 1
      error('+ operator defined for two tsd''s or for one tsd and one scalar');
    end
    s = tsd(a.t, a.data + b);
  elseif (isa(a, 'numeric') & isa(b, 'tsd'))
    if(prod(size(b))) ~= 1
      error('+ operator defined for two tsd''s or for one tsd and one scalar');
    end
    s = tsd(b.t, a + b.data);
  else
    error('+ operator defined for two tsd''s or for one tsd and one scalar');
  end