Description of size
Home > @tsd > size.m
size
PURPOSE
Return the size of the data component (overoad of the size function)
SYNOPSIS
function sz = size(TSA)
DESCRIPTION
  Return the size of the data component (overoad of the size function)
      USAGE:
      sz = size(tsa)
CROSS-REFERENCE INFORMATION
This function calls:
size Return the size of the data component (overoad of the size function)
This function is called by:
FindPeaks Get peaks in data
cat Concatenation of TSD objects
classify Breaks a TSD object in many tsds according to the value of data
intervalFun im = intervalFun(tsa, is, func, options) computes mean of tsa data in each of the intervals in isw
intervalMean Computes mean of of data in each of subset of a given interval
intervalSplit Returns a cell array of tsd object, one for each subset of a given interval
max Returns the maximal value(s) and time(s) of a TSD object (overoads the max function)
minus Overload of the - operator
peaks Get peaks in data
plus Overload of the + operator
size Return the size of the data component (overoad of the size function)
triggeredMeanData Event-triggered mean of the Data component, triggered on events (TODO)
tsd Constructor of TSD object
SOURCE CODE
function sz = size(TSA)
%  Return the size of the data component (overoad of the size function)
%
%      USAGE:
%      sz = size(tsa)
% copyright (c) 2004 Francesco P. Battaglia
% This software is released under the GNU GPL
% www.gnu.org/copyleft/gpl.html
  sz =  size(TSA.data);