Description of subset
Home > @tsd > subset.m
subset
PURPOSE
Returns tsd of a subset of input
SYNOPSIS
function tss = subset(tsa, ix);
DESCRIPTION
  Returns tsd of a subset of input
      USAGE:
      tss = subset(tsa, ix);
      INPUTS:
      ts - an input object
      ix - an array of indices
      OUTPUTS:
      tss - a tsd containing the point in tsa indicated by ix
CROSS-REFERENCE INFORMATION
This function calls:
Data Returns Data of a TSD object
Range Returns TSD timestamps
tsd Constructor of TSD object
This function is called by:
intervalSplit Returns a cell array of tsd object, one for each subset of a given interval
threshold Threshold crossings
thresholdHysteresis Hysteresis thresholding
unique Eliminates points with the same timestamps
SOURCE CODE
function tss = subset(tsa, ix);
%  Returns tsd of a subset of input
%
%      USAGE:
%      tss = subset(tsa, ix);
%
%      INPUTS:
%      ts - an input object
%      ix - an array of indices
%
%      OUTPUTS:
%      tss - a tsd containing the point in tsa indicated by ix
% copyright (c) 2004 Francesco P. Battaglia
% This software is released under the GNU GPL
% www.gnu.org/copyleft/gpl.html
  t = Range(tsa);
  tss = tsd(t(ix), SelectAlongFirstDimension(Data(tsa), ix));