Description of timeSpan
Home > @tsd > timeSpan.m
timeSpan
PURPOSE
Returns interval spanning the duration of a TSD
SYNOPSIS
function is = timeSpan(tsa, TimeUnits)
DESCRIPTION
  Returns interval spanning the duration of a TSD
      USAGE
      is = timeSpan(tsa)
      INPUTS:
      tsa       - a tsd object
      TimeUnits - the time units for the result
      OUTPUT:
      is - intervalSet containing the timestamp
CROSS-REFERENCE INFORMATION
This function calls:
EndTime Returns last timestamp
StartTime Returns first timestamp
This function is called by:
max Returns the maximal value(s) and time(s) of a TSD object (overoads the max function)
SOURCE CODE
function is = timeSpan(tsa, TimeUnits)
%  Returns interval spanning the duration of a TSD
%
%      USAGE
%      is = timeSpan(tsa)
%
%      INPUTS:
%      tsa       - a tsd object
%      TimeUnits - the time units for the result
%
%      OUTPUT:
%      is - intervalSet containing the timestamp
% copyright (c) 2004 Francesco P. Battaglia
% This software is released under the GNU GPL
% www.gnu.org/copyleft/gpl.html
  error(nargchk( 1, 2, nargin));
  if nargin == 1
    TimeUnits = time_units('ts');
  end
  if isa(TimeUnits, 'char');
    TimeUnits = time_units(TimeUnits);
  end
  is = intervalSet(StartTime(tsa), EndTime(tsa));