Description of timeDeriv
Home > @tsd > timeDeriv.m
timeDeriv
PURPOSE
TimeDerivative of a tsd
SYNOPSIS
function S = timeDeriv(tsa, varargin)
DESCRIPTION
  TimeDerivative of a tsd
      USAGE:
      S = timeDeriv(tsa, OptionName, OptionValue, ...)
      This is intended for continuously sampled tsd-s,
      If there are some missing values, they are interpolated before smoothing
      INPUTS:
      tsa - a tsd object
      OUTPUTS:
      S - the derivative tsd
      OPTIONS:
      'PreSmooth', if set the tsd will be smoothed by that amount
CROSS-REFERENCE INFORMATION
This function calls:
Data Returns Data of a TSD object
Range Returns TSD timestamps
Restrict Restrict TSD to a new timestamp
cat Concatenation of TSD objects
interp_missing Interpolate missing values in continuously sampled tsd
length Returns number of elements in tsa (overoads length function)
smooth Smooth a TSD
timeDeriv TimeDerivative of a tsd
tsd Constructor of TSD object
This function is called by:
timeDeriv TimeDerivative of a tsd
SOURCE CODE
function S = timeDeriv(tsa, varargin)
%  TimeDerivative of a tsd
%
%      USAGE:
%      S = timeDeriv(tsa, OptionName, OptionValue, ...)
%
%      This is intended for continuously sampled tsd-s,
%      If there are some missing values, they are interpolated before smoothing
%
%      INPUTS:
%      tsa - a tsd object
%
%      OUTPUTS:
%      S - the derivative tsd
%
%      OPTIONS:
%      'PreSmooth', if set the tsd will be smoothed by that amount
% copyright (c) 2004 Francesco P. Battaglia
% This software is released under the GNU GPL
% www.gnu.org/copyleft/gpl.html
opt_varargin = varargin;
defined_options = dictArray(...
    { { 'PreSmooth', {0, {'numeric'} } } ,
    {'InIntervals', { {}, {'cell'} } } } );
getOpt;
if ~isempty(InIntervals)
    for i = 1:length(InIntervals)
         tsdR{i} = Restrict(tsa, InIntervals{i});
        tsdR{i} = timeDeriv(tsdR{i}, 'PreSmooth', PreSmooth);
    end
    S = cat(tsdR{:});
    return
end
if PreSmooth
    tsa = smooth(tsa, PreSmooth);
else
    tsa = interp_missing(tsa);
end
 t = Range(tsa);
  S = tsd(t(1:end-1), diff(Data(tsa)) ./ diff(t));