Description of End
Home > @intervalSet > End.m
End
PURPOSE
Ending time of the intervalSet object
SYNOPSIS
function S = End(O, TimeUnits)
DESCRIPTION
  Ending time of the intervalSet object
      USAGE:
      S = End(O, TimeUnits)
      INPUTS:
      O - a ts object
      TimeUnits - a units object or the abbreviation string
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
belong Tells whether timestamps belong to a intervalSet
cat Concatenates IntervalSet objects
dropLongIntervals Drops the intervals in the set that are longer than a given threshold
dropShortIntervals Drops the intervals in the set that are shorter than a given threshold
inInterval Tells whether points are contained in intervalSet (TODO)
length Returns the length of each interval in the set
regIntervals Split an intervalSet object in N segments of equal length
timeSpan Returns the minimum continuous interval that contains the intervalSet
tot_length Returns total length of intervalSet
SOURCE CODE
function S = End(O, TimeUnits)
%  Ending time of the intervalSet object
%
%      USAGE:
%      S = End(O, TimeUnits)
%
%      INPUTS:
%      O - a ts object
%      TimeUnits - a units object or the abbreviation string
% copyright (c) 2004 Francesco P. Battaglia
% This software is released under the GNU GPL
% www.gnu.org/copyleft/gpl.html
  if nargin < 1 | nargin > 2
    error('Call with one or two arguments');
  end
 if nargin == 1
    TimeUnits = time_units('ts');
  end
  S = O.stop;
  if isa(TimeUnits, 'char')
    TimeUnits = time_units(TimeUnits);
  end
  cnvrt = convert(O.units, TimeUnits);
  if cnvrt ~= 1
    S = S * cnvrt;
  end