Description of mergeCloseIntervals
Home > @intervalSet > mergeCloseIntervals.m
mergeCloseIntervals
PURPOSE
Merge together intervals that are closer than a given threshold
SYNOPSIS
function iso = mergeCloseIntervals(is, thr, varargin)
DESCRIPTION
  Merge together intervals that are closer than a given threshold
      USAGE:
      iso = mergeCloseIntervals(is, thr, OptionName, OptionValue)
      INPUTS:
      is  - an intervalSet
      thr - a distance threshold; if two consecutive intervals are closer than
            thr they will be merged
      OUTPUTS:
      iso - the resulting intervalSet
CROSS-REFERENCE INFORMATION
This function calls:
dropShortIntervals Drops the intervals in the set that are shorter than a given threshold
length Returns the length of each interval in the set
timeSpan Returns the minimum continuous interval that contains the intervalSet
This function is called by:
SOURCE CODE
function iso = mergeCloseIntervals(is, thr, varargin)
%  Merge together intervals that are closer than a given threshold
%
%      USAGE:
%      iso = mergeCloseIntervals(is, thr, OptionName, OptionValue)
%
%      INPUTS:
%      is  - an intervalSet
%      thr - a distance threshold; if two consecutive intervals are closer than
%            thr they will be merged
%
%      OUTPUTS:
%      iso - the resulting intervalSet
% copyright (c) 2004 Francesco P. Battaglia
% This software is released under the GNU GPL
% www.gnu.org/copyleft/gpl.html
  opt_varargin = varargin;
  defined_options = dictArray( ...
  { { 'TimeUnits', {time_units('ts'), {'char', 'units'} } } } );
  getOpt;
  cnvrt = convert(TimeUnits, is.units);
  thr = thr * cnvrt;
if length(is.start)>0
  tsp = timeSpan(is);
  df = tsp- is;
  df = dropShortIntervals(df, thr);
  iso = tsp - df;
else
  iso = is;
end