%constants for sorting. see spikesortingParameters.txt for explanations.

CLUSTERID_NOISE_CLUSTER=99999999;

%extraction method
METHOD_EXTRACTION_POWER=1;
METHOD_EXTRACTION_AMPP=2;
METHOD_EXTRACTION_AMPN=3;
METHOD_EXTRACTION_AMPA=4;
METHOD_EXTRACTION_WDM=5;


%alignment/peak finding method
METHOD_PEAKFIND_FINDPEAK=1;
METHOD_PEAKFIND_NONE=2;
METHOD_PEAKFIND_POWER=3;
METHOD_PEAKFIND_MTEO=4;
