Description of mtfftc
mtfftc
PURPOSE
Multi-taper fourier transform - continuous data
SYNOPSIS
function J=mtfftc(data,tapers,nfft,Fs)
DESCRIPTION
 Multi-taper fourier transform - continuous data
 Usage:
 J=mtfftc(data,tapers,nfft,Fs) - all arguments required
 Input:
       data (in form samples x channels/trials or a single vector)
       tapers (precalculated tapers from dpss)
       nfft (length of padded data)
       Fs   (sampling frequency)
 Output:
       J (fft in form frequency index x taper index x channels/trials)
CROSS-REFERENCE INFORMATION
This function calls:
change_row_to_column Helper routine to transform 1d arrays into column vectors that are needed
This function is called by:
CrossSpecMat
CrossSpecMatc Multi-taper cross-spectral matrix - another routine, allows for multiple trials and channels
coherencyc Multi-taper coherency,cross-spectrum and individual spectra - continuous process
coherencyc_unequal_length_trials This routine computes the average multi-taper coherence for a given set of unequal length segments. It is
cohmatrixc Multi-taper coherency,cross-spectral matrix - continuous process
ftestc computes the F-statistic for sine wave in locally-white noise (continuous data).
mtdspectrumc Multi-taper frequency derivative of the spectrum - continuous process
mtspectrumc Multi-taper spectrum - continuous process
mtspectrumc_unequal_length_trials This routine computes the multi-taper spectrum for a given set of unequal length segments. It is
mtspectrumsegc Multi-taper segmented spectrum for a univariate continuous process
nonst_stat Nonstationarity test - continuous process
coherencycpb Multi-taper coherency,cross-spectrum and individual spectra - continuous and binned point process data
coherencycpt Multi-taper coherency,cross-spectrum and individual spectra -continuous data and point process as times
SOURCE CODE
function J=mtfftc(data,tapers,nfft,Fs)
% Multi-taper fourier transform - continuous data
%
% Usage:
% J=mtfftc(data,tapers,nfft,Fs) - all arguments required
% Input:
%       data (in form samples x channels/trials or a single vector)
%       tapers (precalculated tapers from dpss)
%       nfft (length of padded data)
%       Fs   (sampling frequency)
%
% Output:
%       J (fft in form frequency index x taper index x channels/trials)
if nargin < 4; error('Need all input arguments'); end;
data=change_row_to_column(data);
[NC,C]=size(data); % size of data
[NK K]=size(tapers); % size of tapers
if NK~=NC; error('length of tapers is incompatible with length of data'); end;
tapers=tapers(:,:,ones(1,C)); % add channel indices to tapers
data=data(:,:,ones(1,K)); % add taper indices to data
data=permute(data,[1 3 2]); % reshape data to get dimensions to match those of tapers
data_proj=data.*tapers; % product of data with tapers
J=fft(data_proj,nfft)/Fs;   % fft of projected data