function [redraw, rekey, undoable] = RunKKwik(iClust)

% RunKlustaKwik(iClust)
%
% Runs KlustaKwik on a single cluster
% 
%
% INPUTS
%    iClust
%
% OUTPUTS
%
% NONE
% TO USE WITH MCLUST, put this in the MClust/ClusterOptions folder

% NCST 2003 
% 
% simple mods ADR 208

redraw = false; rekey = false; undoable = false;

global MClust_Directory

% Locate and load the names of feature files
featureFiles =  sortcell(FindFiles('feature_*.m', ...
    'StartingDirectory', fullfile(MClust_Directory, 'Features') ,'CheckSubdirs', 0));
featureIgnoreString = {};
featureUseString = {};
featuresToUse = {};
for iF = 1:length(featureFiles)
   [dummy, featureFiles{iF}] = fileparts(featureFiles{iF});
   featureFiles{iF} = featureFiles{iF}(9:end); % cut "feature_" off front for display
   if any(strcmp(featureFiles{iF}, featuresToUse))
      featureUseString = cat(1, featureUseString, featureFiles(iF));
   else
      featureIgnoreString = cat(1, featureIgnoreString, featureFiles(iF));
   end
end

CutOnBestProjFigure = figure('Name','Run KlustaKwik','Units', 'Normalized', 'UserData', iClust, 'Tag', 'RunKlustaKwik');
%-------------------------------
% Alignment variables

uicHeight = 0.04;
uicWidth  = 0.25;
dX = 0.3;
XLocs = 0.1:dX:0.9;
dY = 0.04;
YLocs = 0.9:-dY:0.1;
FrameBorder = 0.01;

% Create Feature Listboxes
uicontrol('Parent', CutOnBestProjFigure,...
	'Style', 'text', 'String', 'FEATURES', 'Units', 'Normalized', 'Position', [XLocs(1) YLocs(4) 2*uicWidth uicHeight]);
uicontrol('Parent', CutOnBestProjFigure,...
	'Style', 'text', 'String', 'Available', 'Units', 'Normalized', 'Position', [XLocs(1) YLocs(5) uicWidth uicHeight]);
ui_featuresIgnoreLB =  uicontrol('Parent', CutOnBestProjFigure,...
	'Units', 'Normalized', 'Position', [XLocs(1) YLocs(17) uicWidth 12*uicHeight],...
	'Style', 'listbox', 'Tag', 'FeaturesIgnoreListbox',...
	'Callback', 'MClustCallbacks',...
	'HorizontalAlignment', 'right', ...
	'Enable','on', ...
	'TooltipString', 'These are features which are not included but are also available.');
uicontrol('Parent',CutOnBestProjFigure,...
	'Style', 'text', 'String', 'Use', 'Units', 'Normalized', 'Position', [XLocs(1)+uicWidth YLocs(5) uicWidth uicHeight]);
ui_featuresUseLB = uicontrol('Parent', CutOnBestProjFigure,...
	'Units', 'Normalized', 'Position', [XLocs(1)+uicWidth YLocs(17) uicWidth 12*uicHeight],...
	'Style', 'listbox', 'Tag', 'FeaturesUseListbox',...
	'Callback', 'MClustCallbacks',...
	'HorizontalAlignment', 'right', ...
	'Enable','on', ...
	'TooltipString', 'These features will be used for cluster separation.');

set(ui_featuresIgnoreLB, 'UserData', ui_featuresUseLB);
set(ui_featuresUseLB,    'UserData', ui_featuresIgnoreLB);

set(ui_featuresIgnoreLB, 'String', featureIgnoreString);
set(ui_featuresUseLB, 'String', featureUseString);

uicontrol('Parent',CutOnBestProjFigure, ...
	'Units', 'Normalized', 'Position', [XLocs(1) + uicWidth/2 YLocs(1) uicWidth/2 uicHeight], ...
	'Style', 'text','Tag', 'RunKlustaKwikiClust', 'String', num2str(iClust), ...
	'TooltipString', 'Cluster 1');	
uicontrol('Parent',CutOnBestProjFigure, ...
	'Units', 'Normalized', 'Position', [XLocs(1) + uicWidth/2 YLocs(2) uicWidth/2 uicHeight], ...
	'Style', 'edit', 'String', num2str(2), ...
	'TooltipString', 'Mininum number of clusters', 'Tag','RunKlustaKwikMinClust');
uicontrol('Parent',CutOnBestProjFigure, ...
	'Units', 'Normalized', 'Position', [XLocs(1) + uicWidth/2 YLocs(3) uicWidth/2 uicHeight], ...
	'Style', 'edit', 'String', num2str(7), ...
	'TooltipString', 'Maximum number of clusters', 'Tag','RunKlustaKwikMaxClust');

uicontrol('Parent',CutOnBestProjFigure, ...
	'Units', 'Normalized', 'Position', [XLocs(1) YLocs(1) uicWidth/2 uicHeight], ...
	'Style', 'text','String', 'Cluster');	
uicontrol('Parent',CutOnBestProjFigure, ...
	'Units', 'Normalized', 'Position', [XLocs(1) YLocs(2) uicWidth/2 uicHeight], ...
	'Style', 'text','String', 'minClusters');	
uicontrol('Parent',CutOnBestProjFigure, ...
	'Units', 'Normalized', 'Position', [XLocs(1) YLocs(3) uicWidth/2 uicHeight], ...
	'Style', 'text','String', 'maxClusters');	

uicontrol('Parent',CutOnBestProjFigure, ...
	'Units', 'Normalized', 'Position', [XLocs(1) YLocs(20) uicWidth uicHeight], ...
	'Style', 'pushbutton','Tag', 'AcceptFeatures_FBS', 'String', 'Accept features', 'Callback', 'RunKKwik_Callbacks', ...
	'TooltipString', 'Accept features to use clustering the current cluster');
uicontrol('Parent',CutOnBestProjFigure, ...
	'Units', 'Normalized', 'Position', [XLocs(1) YLocs(21) uicWidth uicHeight], ...
	'Style', 'pushbutton', 'String', 'Cancel', 'Callback', 'close');