Description of getparams
getparams
PURPOSE
Helper function to convert structure params to variables used by the
SYNOPSIS
function [tapers,pad,Fs,fpass,err,trialave,params]=getparams(params)
DESCRIPTION
 Helper function to convert structure params to variables used by the
 various routines - also performs checks to ensure that parameters are
 defined; returns default values if they are not defined.
 Usage: [tapers,pad,Fs,fpass,err,trialave,params]=getparams(params)
 Inputs:
       params: structure with fields tapers, pad, Fs, fpass, err, trialave
           - optional
             tapers : precalculated tapers from dpss or in the one of the following
                       forms:
                       (1) A numeric vector [TW K] where TW is the
                           time-bandwidth product and K is the number of
                           tapers to be used (less than or equal to
                           2TW-1).
                       (2) A numeric vector [W T p] where W is the
                           bandwidth, T is the duration of the data and p
                           is an integer such that 2TW-p tapers are used. In
                           this form there is no default i.e. to specify
                           the bandwidth, you have to specify T and p as
                           well. Note that the units of W and T have to be
                            consistent: if W is in Hz, T must be in seconds
                             and vice versa. Note that these units must also
                            be consistent with the units of params.Fs: W can
                            be in Hz if and only if params.Fs is in Hz.
                           The default is to use form 1 with TW=3 and K=5
            pad            (padding factor for the FFT) - optional (can take values -1,0,1,2...).
                    -1 corresponds to no padding, 0 corresponds to padding
                    to the next highest power of 2 etc.
                       e.g. For N = 500, if PAD = -1, we do not pad; if PAD = 0, we pad the FFT
                       to 512 points, if pad=1, we pad to 1024 points etc.
                       Defaults to 0.
           Fs   (sampling frequency) - optional. Default 1.
           fpass    (frequency band to be used in the calculation in the form
                                   [fmin fmax])- optional.
                                   Default all frequencies between 0 and Fs/2
           err  (error calculation [1 p] - Theoretical error bars; [2 p] - Jackknife error bars
                                   [0 p] or 0 - no error bars) - optional. Default 0.
           trialave (average over trials when 1, don't average when 0) - optional. Default 0
 Outputs:
 The fields listed above as well as the struct params. The fields are used
 by some routines and the struct is used by others. Though returning both
 involves overhead, it is a safer, simpler thing to do.
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
CrossSpecMat
CrossSpecMatc Multi-taper cross-spectral matrix - another routine, allows for multiple trials and channels
coherencyc Multi-taper coherency,cross-spectrum and individual spectra - continuous process
coherencyc_unequal_length_trials This routine computes the average multi-taper coherence for a given set of unequal length segments. It is
coherencysegc Multi-taper coherency, cross-spectrum and individual spectra with segmenting - continuous process
cohgramc Multi-taper time-frequency coherence,cross-spectrum and individual spectra - continuous processes
cohmatrixc Multi-taper coherency,cross-spectral matrix - continuous process
fitlinesc fits significant sine waves to data (continuous data).
ftestc computes the F-statistic for sine wave in locally-white noise (continuous data).
mtdspecgramc Multi-taper derivative of the time-frequency spectrum - continuous process
mtdspectrumc Multi-taper frequency derivative of the spectrum - continuous process
mtpowerandfstatc Multi-taper computation of the power and the fstatistic for a particular frequency - continuous process
mtspecgramc Multi-taper time-frequency spectrum - continuous process
mtspecgramtrigc Multi-taper event triggered time-frequency spectrum - continuous process
mtspectrum_of_spectrumc Multi-taper segmented, second spectrum (spectrum of the log spectrum) for a continuous process
mtspectrumc Multi-taper spectrum - continuous process
mtspectrumc_unequal_length_trials This routine computes the multi-taper spectrum for a given set of unequal length segments. It is
mtspectrumsegc Multi-taper segmented spectrum for a univariate continuous process
mtspectrumtrigc Multi-taper event triggered time-frequency spectrum - continuous process
nonst_stat Nonstationarity test - continuous process
rmlinesc removes significant sine waves from data (continuous data).
rmlinesmovingwinc fits significant sine waves to data (continuous data) using overlapping windows.
spsvd Space frequency SVD of input data - continuous processes
coherencycpb Multi-taper coherency,cross-spectrum and individual spectra - continuous and binned point process data
coherencycpt Multi-taper coherency,cross-spectrum and individual spectra -continuous data and point process as times
coherencysegcpb Multi-taper coherency,cross-spectrum and individual spectra with segmenting
coherencysegcpt Multi-taper coherency,cross-spectrum and individual spectra computed by segmenting
cohgramcpb Multi-taper time-frequency coherence,cross-spectrum and individual spectra
cohgramcpt Multi-taper time-frequency coherence,cross-spectrum and individual spectra
CrossSpecMatpb
coherencypb Multi-taper coherency,cross-spectrum and individual spectra - binned point process
coherencysegpb Multi-taper coherency,cross-spectrum and individual spectra computed by segmenting
cohgrampb Multi-taper time-frequency coherence,cross-spectrum and individual spectra - two binned point processes
cohmatrixpb Multi-taper coherency matrix - binned point process
mtdspecgrampb Multi-taper derivatives of time-frequency spectrum - binned point process
mtdspectrumpb Multi-taper spectral derivative - binned point process
mtspecgrampb Multi-taper time-frequency spectrum - binned point process
mtspecgramtrigpb Multi-taper event triggered time-frequency spectrum - binned point process
mtspectrumpb Multi-taper spectrum - binned point process
mtspectrumsegpb Multi-taper segmented spectrum for a univariate binned point process
mtspectrumtrigpb Multi-taper event triggered time-frequency spectrum - binned point process
CrossSpecMatpt
coherencypt Multi-taper coherency - point process times
coherencysegpt Multi-taper coherency computed by segmenting two univariate point processes into chunks
cohgrampt Multi-taper time-frequency coherence - two point processes given as times
cohmatrixpt Multi-taper coherency matrix - point process times
mtdspecgrampt Multi-taper derivative time-frequency spectrum - point process times
mtdspectrumpt Multi-taper spectral derivative - point process times
mtspecgrampt Multi-taper time-frequency spectrum - point process times
mtspecgramtrigpt Multi-taper event triggered time-frequency spectrum - point process times
mtspectrumpt Multi-taper spectrum - point process times
mtspectrumsegpt Multi-taper segmented spectrum for a univariate binned point process
mtspectrumtrigpt Multi-taper time-frequency spectrum - point process times
mtspecgramc_fast Multi-taper time-frequency spectrum - continuous process
mtspecgramc_slow Multi-taper time-frequency spectrum - continuous process
SOURCE CODE
function [tapers,pad,Fs,fpass,err,trialave,params]=getparams(params)
% Helper function to convert structure params to variables used by the
% various routines - also performs checks to ensure that parameters are
% defined; returns default values if they are not defined.
%
% Usage: [tapers,pad,Fs,fpass,err,trialave,params]=getparams(params)
%
% Inputs:
%       params: structure with fields tapers, pad, Fs, fpass, err, trialave
%           - optional
%             tapers : precalculated tapers from dpss or in the one of the following
%                       forms:
%                       (1) A numeric vector [TW K] where TW is the
%                           time-bandwidth product and K is the number of
%                           tapers to be used (less than or equal to
%                           2TW-1).
%                       (2) A numeric vector [W T p] where W is the
%                           bandwidth, T is the duration of the data and p
%                           is an integer such that 2TW-p tapers are used. In
%                           this form there is no default i.e. to specify
%                           the bandwidth, you have to specify T and p as
%                           well. Note that the units of W and T have to be
%                            consistent: if W is in Hz, T must be in seconds
%                             and vice versa. Note that these units must also
%                            be consistent with the units of params.Fs: W can
%                            be in Hz if and only if params.Fs is in Hz.
%                           The default is to use form 1 with TW=3 and K=5
%
%            pad            (padding factor for the FFT) - optional (can take values -1,0,1,2...).
%                    -1 corresponds to no padding, 0 corresponds to padding
%                    to the next highest power of 2 etc.
%                       e.g. For N = 500, if PAD = -1, we do not pad; if PAD = 0, we pad the FFT
%                       to 512 points, if pad=1, we pad to 1024 points etc.
%                       Defaults to 0.
%           Fs   (sampling frequency) - optional. Default 1.
%           fpass    (frequency band to be used in the calculation in the form
%                                   [fmin fmax])- optional.
%                                   Default all frequencies between 0 and Fs/2
%           err  (error calculation [1 p] - Theoretical error bars; [2 p] - Jackknife error bars
%                                   [0 p] or 0 - no error bars) - optional. Default 0.
%           trialave (average over trials when 1, don't average when 0) - optional. Default 0
% Outputs:
% The fields listed above as well as the struct params. The fields are used
% by some routines and the struct is used by others. Though returning both
% involves overhead, it is a safer, simpler thing to do.
if ~isfield(params,'tapers') || isempty(params.tapers);  %If the tapers don't exist
     display('tapers unspecified, defaulting to params.tapers=[3 5]');
     params.tapers=[3 5];
end;
if ~isempty(params) && length(params.tapers)==3
    % Compute timebandwidth product
    TW = params.tapers(2)*params.tapers(1);
    % Compute number of tapers
    K  = floor(2*TW - params.tapers(3));
    params.tapers = [TW  K];
end
if ~isfield(params,'pad') || isempty(params.pad);
    params.pad=0;
end;
if ~isfield(params,'Fs') || isempty(params.Fs);
    params.Fs=1;
end;
if ~isfield(params,'fpass') || isempty(params.fpass);
    params.fpass=[0 params.Fs/2];
end;
if ~isfield(params,'err') || isempty(params.err);
    params.err=0;
end;
if ~isfield(params,'trialave') || isempty(params.trialave);
    params.trialave=0;
end;
tapers=params.tapers;
pad=params.pad;
Fs=params.Fs;
fpass=params.fpass;
err=params.err;
trialave=params.trialave;