Description of test_nex
test_nex
PURPOSE
SYNOPSIS
This is a script file.
DESCRIPTION
CROSS-REFERENCE INFORMATION
This function calls:
nex_cont nex_cont(filename, varname): Read continuous variable from a .nex file
nex_info nex_info(filename) -- read and display .nex file info
nex_marker nex_marker(filename, varname): Read a marker variable from a .nex file
nex_ts nex_ts(filename, varname): Read timestamps from a .nex file
nex_wf nex_wf(filename, varname): Read waveform variable from a .nex file
This function is called by:
SOURCE CODE
[nvar, names, types] = nex_info('test.nex');
[n, ts] = nex_ts('test.nex', 'neuron1');
[adfreq, n, ts, fn, d] = nex_cont('test.nex', 'continuous1');
[adfreq, n, ts, nf, w] = nex_wf('test.nex', 'wave1');
[n, nm, nl, ts, names, m] = nex_marker('test.nex', 'marker1');