Description of LoadPosition
Home > Wrappers > LoadPosition.m
LoadPosition
PURPOSE
Intermediate wrapper, should not be used directly
SYNOPSIS
function [whl,t,GoodRanges] = LoadPosition(fbasename)
DESCRIPTION
 Intermediate wrapper, should not be used directly
 USAGE
 [whl,t,GoodRanges,ep] = LoadPosition(fbasename)
 OUTPUT:
   whl: the position matrix
   t: time vector
   Good Ranges:
CROSS-REFERENCE INFORMATION
This function calls:
CleanWhlForR Position file cleaning
This function is called by:
HeadDirection_Wrapper loads head-direction from a position file file (ending in .whl)
LoadPosition_Wrapper loads position and speed from a position file file (ending in .whl)
SOURCE CODE
function [whl,t,GoodRanges] = LoadPosition(fbasename)
% Intermediate wrapper, should not be used directly
%
% USAGE
% [whl,t,GoodRanges,ep] = LoadPosition(fbasename)
%
% OUTPUT:
%   whl: the position matrix
%   t: time vector
%   Good Ranges:
Fs = 1250/32;
whlt = dlmread([fbasename '.whl']);
[whl GoodRanges] = CleanWhlForR(whlt);
t = (1:size(whlt,1))'/Fs;
GoodRanges = GoodRanges/Fs;