Description of fitted
fitted
PURPOSE
Fitted values from a locfit object.
SYNOPSIS
function y = fitted(fit)
DESCRIPTION
 Fitted values from a locfit object.
 Input arguments:
   fit - the locfit() fit.
  Author: Catherine Loader.
CROSS-REFERENCE INFORMATION
This function calls:
backtr
predict Interpolate a fit produced by locfit().
This function is called by:
fig5_5 Local Regression and Likelihood, Figure 5.5.
fig6_4 Local Regression and Likelihood, Figure 6.4.
fig6_5 Local Regression and Likelihood, Figure 6.5.
fig8_1 Local Regression and Likelihood, Figure 8.1.
fig8_3 Local Regression and Likelihood, Figure 8.3.
lf_censor
SOURCE CODE
function y = fitted(fit)
% Fitted values from a locfit object.
%
% Input arguments:
%   fit - the locfit() fit.
%
%  Author: Catherine Loader.
z = predict(fit,'d','restyp','fit');
y = backtr(z,fit);
return;