Description of invlink
invlink
PURPOSE
inverse link function for locfit.
SYNOPSIS
function y0 = invlink(y,fali)
DESCRIPTION
 inverse link function for locfit.
 y is a vector of raw fitted values.
 fali is the integer [family link] vector from locfit.
 output is the inv. link.
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
lfband adds confidence bands around the plot of a locfit() fit.
lfplot Plot (for one or two dimensions) a locfit() fit.
smooth_lf must (unlike R smooth.lf() function) give x and y.
den_jack Function to compute smooth estimates of the mean of x using locfit,
SOURCE CODE
function y0 = invlink(y,fali)
% inverse link function for locfit.
% y is a vector of raw fitted values.
% fali is the integer [family link] vector from locfit.
% output is the inv. link.
link = fali(2);
switch(link)
    case 3   % identity
        y0 = y;
    case 4   % log
        y0 = exp(y);
    case 5   % logit - should invert carefully!
        y0 = 1 - 1./(1+exp(y));
    case 6   % inverse
        y0 = 1/y;
    case 7   % sqrt
        y0 = y*abs(y);
    case 8   % arcsin
        y0 = sin(y)*sin(y);
    otherwise
        disp('invlink: Unknown link function');
end;