Description of lfband
lfband
PURPOSE
adds confidence bands around the plot of a locfit() fit.
SYNOPSIS
function lfband(fit,varargin)
DESCRIPTION
 adds confidence bands around the plot of a locfit() fit.
 for 2-d fits, produces separate surface plots of upper and
 lower confidence limits.
 Bands are based on 95% pointwise coverage, using a single
 (i.e. global) estimate of sigma^2.
CROSS-REFERENCE INFORMATION
This function calls:
invlink inverse link function for locfit.
lfmarg computes grid margins from a locfit object, used for plotting.
predict Interpolate a fit produced by locfit().
This function is called by:
fig4_1 Local Regression and Likelihood, Figure 4.1.
fig4_2 Local Regression and Likelihood, Figure 4.2.
lfex1 Local Estimation a spike firing rate (in spikes per unit time).
lfex2 Model the success probability of successive trials of a monkey
den_jack Function to compute smooth estimates of the mean of x using locfit,
SOURCE CODE
function lfband(fit,varargin)
% adds confidence bands around the plot of a locfit() fit.
%
% for 2-d fits, produces separate surface plots of upper and
% lower confidence limits.
%
% Bands are based on 95% pointwise coverage, using a single
% (i.e. global) estimate of sigma^2.
xfit = lfmarg(fit);
% placing 'band','g' before varargin{:} ensures that
% user-provided 'band' has precedence.
ypp = predict(fit,xfit,'band','g',varargin{:});
yfit = ypp{1};
se = ypp{2};
bands = ypp{3};
data = fit.data;
xdata = data.x;
p = size(xdata,2);
cv = 1.96;
fali = fit.fit_points.family_link;
cl = invlink(bands(:,1),fali);
cu = invlink(bands(:,2),fali);
if (p==1)
  hold on;
  plot(xfit{1},cu,':');
  plot(xfit{1},cl,':');
  hold off;
end;
if (p==2)
  x1 = xfit{1};
  x2 = xfit{2};
  figure(1);
  surf(x1,x2,reshape(cl,length(x1),length(x2))');
  figure(2);
  surf(x1,x2,reshape(cu,length(x1),length(x2))');
end;
return;