Description of lfknots
lfknots
PURPOSE
SYNOPSIS
function z=lfknots(fit,varargin)
DESCRIPTION
 very spartan version of the S lfknots function...
 Author: Catherine Loader.
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
fig10_1 Local Regression and Likelihood, Figure 10.1.
hatmatrix
smooth_lf must (unlike R smooth.lf() function) give x and y.
SOURCE CODE
function z=lfknots(fit,varargin)
%
% very spartan version of the S lfknots function...
%
% Author: Catherine Loader.
z = fit.fit_points.fitted_values;
return;