Description of items
Home > @dictArray > items.m
items
PURPOSE
returns cell arry of key/value pairs in O
SYNOPSIS
function it = items(O)
DESCRIPTION
 returns cell arry of key/value pairs in O
CROSS-REFERENCE INFORMATION
This function calls:
keys dictArray/keys K = keys(D) returns keys of dictArray D
length l = length(D) returns number of items in dictArray D
values dictArray/values v = values(D) returns cell array of values in dictArray D
This function is called by:
SOURCE CODE
function it = items(O)
% returns cell arry of key/value pairs in O
% copyright (c) 2004 Francesco P. Battaglia
% This software is released under the GNU GPL
% www.gnu.org/copyleft/gpl.html
keys = O.keys;
values = O.values;
l = length(keys);
it = cell(l,1);
for i = 1:l
  it{i} = { keys{i}, values{i}  };
end