Description of values
Home > @dictArray > values.m
values
PURPOSE
dictArray/values v = values(D) returns cell array of values in dictArray D
SYNOPSIS
function v = values(O)
DESCRIPTION
 dictArray/values v = values(D) returns cell array of values in dictArray D
 v = is a cell array
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
del D = del(D,k) deletes item with key k in dictArray D
dictArray O = dictArray(inp) constructor for the dictArray class, inspired to
items returns cell arry of key/value pairs in O
update D = update(D, A) updates all the items in D with corresponding items in A
SOURCE CODE
function v = values(O)
% dictArray/values v = values(D) returns cell array of values in dictArray D
%
% v = is a cell array
% copyright (c) 2004 Francesco P. Battaglia
% This software is released under the GNU GPL
% www.gnu.org/copyleft/gpl.html
  v = O.values;