Description of abs
Home > @tsd > abs.m
abs
PURPOSE
Absolute value of the data
SYNOPSIS
function a = abs(tsa)
DESCRIPTION
 Absolute value of the data
  USAGE:
  tso = abs(tsa)
  INPUT:
  tsa: a tsd object
  OUTPUT:
  tso: a tsd of absolute value
 copyright (c) 2004 Francesco P. Battaglia
 This software is released under the GNU GPL
 www.gnu.org/copyleft/gpl.html
CROSS-REFERENCE INFORMATION
This function calls:
abs Absolute value of the data
tsd Constructor of TSD object
This function is called by:
FindPeaks Get peaks in data
abs Absolute value of the data
compatible_ts Tells whether two tsd's have the same timestamps, within relative tolerance
peaks Get peaks in data
SOURCE CODE
function a = abs(tsa)
% Absolute value of the data
%
%  USAGE:
%  tso = abs(tsa)
%
%  INPUT:
%  tsa: a tsd object
%
%  OUTPUT:
%  tso: a tsd of absolute value
%
% copyright (c) 2004 Francesco P. Battaglia
% This software is released under the GNU GPL
% www.gnu.org/copyleft/gpl.html
  a = tsd(tsa.t, abs(tsa.data), 'TimeUnits', tsa.time_unit);