Description of compatible_ts
Home > @tsd > compatible_ts.m
compatible_ts
PURPOSE
Tells whether two tsd's have the same timestamps, within relative tolerance
SYNOPSIS
function t = compatible_ts(tsa, tsb, tl)
DESCRIPTION
 Tells whether two tsd's have the same timestamps, within relative tolerance
      USAGE:
      t = compatible_ts(tsa, tsb, tol)
      INPUTS:
      tsa,tsb: two tsd to compare
      tol: tolerance (default 0)
      OUPUTS:
      t: scalar value
 copyright (c) 2004 Francesco P. Battaglia
 This software is released under the GNU GPL
 www.gnu.org/copyleft/gpl.html
CROSS-REFERENCE INFORMATION
This function calls:
abs Absolute value of the data
length Returns number of elements in tsa (overoads length function)
This function is called by:
horzcat Horizontal concatenation of TSDs (overload of the [a, b] operator)
minus Overload of the - operator
plus Overload of the + operator
rdivide Overload of the ./ operator for two tsd objects
times Overload of the .* operator
SOURCE CODE
function t = compatible_ts(tsa, tsb, tl)
% Tells whether two tsd's have the same timestamps, within relative tolerance
%
%      USAGE:
%      t = compatible_ts(tsa, tsb, tol)
%
%      INPUTS:
%      tsa,tsb: two tsd to compare
%      tol: tolerance (default 0)
%
%      OUPUTS:
%      t: scalar value
%
% copyright (c) 2004 Francesco P. Battaglia
% This software is released under the GNU GPL
% www.gnu.org/copyleft/gpl.html
  tol = 0;
  if nargin > 2
    tol = tl;
  end
  t = 0;
  if length(tsa.t) ~= length(tsb.t)
    return
  end
  t = all((2 * abs(tsa.t -tsb.t) ./ (abs(tsa.t) + abs(tsb.t)+eps)) < tol );