Description of Range
Home > @tsd > Range.m
Range
PURPOSE
Returns TSD timestamps
SYNOPSIS
function R = Range(tsa, tsflag)
DESCRIPTION
 Returns TSD timestamps
  USAGE:
  R = Range(tsa)
  R = Range(tsa, tsflag)
  OPTIONS:
  tsflag - if 'ts' returns time in timestamps (default),
          if 'sec' returns time in sec
          if 'ms' returns time in ms
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
CrossCorr Computes cross-correlation between TSD objects
FindPeaks Get peaks in data
Restrict Restrict TSD to a new timestamp
cat Concatenation of TSD objects
instantRate Computes instantaneous rate as the inverse of inter-event interval
interp_missing Interpolate missing values in continuously sampled tsd
intervalFun im = intervalFun(tsa, is, func, options) computes mean of tsa data in each of the intervals in isw
intervalMean Computes mean of of data in each of subset of a given interval
intervalSplit Returns a cell array of tsd object, one for each subset of a given interval
length Returns number of elements in tsa (overoads length function)
median_dt Find the median value of inter-event interval
peaks Get peaks in data
smooth Smooth a TSD
subset Returns tsd of a subset of input
thresholdIntervals Returns intervals in which a TSD is above (below) threshold
timeDeriv TimeDerivative of a tsd
triggeredDataMat Returns a event-by-events matrix of Data component triggered on a reference (TODO!)
triggeredMeanData Event-triggered mean of the Data component, triggered on events (TODO)
unique Eliminates points with the same timestamps
SOURCE CODE
function R = Range(tsa, tsflag)
% Returns TSD timestamps
%
%  USAGE:
%  R = Range(tsa)
%  R = Range(tsa, tsflag)
%
%  OPTIONS:
%  tsflag - if 'ts' returns time in timestamps (default),
%          if 'sec' returns time in sec
%          if 'ms' returns time in ms
% ADR
% version L4.1
% status: PROMOTED
% v4.1 28 oct 1998 flag no longer optional.
  if nargin == 2
    if isa(tsflag, 'units')
      ;
    elseif isa(tsflag, 'char')
      tsflag = time_units(tsflag);
    else
      error('tsflag must be time_units, or string');
    end
  else
    tsflag = tsa.time_unit; %defaults to ts
  end
  cnvrt = convert(tsa.time_unit, tsflag);
  if cnvrt ~= 1
    R = tsa.t * cnvrt;
  else
    R = tsa.t;
  end