Description of tsd
Home > @tsd > tsd.m
tsd
PURPOSE
Constructor of TSD object
SYNOPSIS
function tsa = tsd(t, Data, varargin)
DESCRIPTION
 Constructor of TSD object
      USAGE:
      tsa = tsd(t,data, 'optionName1', optionValue1,... )
  tsd is a class of "timestamped arrays"
  composed of an array of timestamp (column vector), and an array of data
  associated to each timestamp (first index corresponding to time).
  data maybe empty, for 0-dimensional data (for example ts
  data). Othewise first dimension must be same as length of timestamp
  vector
  timestamps are assumed to be sorted. If this is not the case, the
  constructor failes, unless the fixOrder option is set
  options may include the following:
  'TimeUnits' - the unit in which the time is expressed (defaults to
           ts=1/10000s)
  'DataUnits' - the unit in which data are expressed (for the moment same
           for all the data)
  'fixOrder'    - if set to nonzero, constructor will reorder the timestamps,
            in the case they are not sorted.
CROSS-REFERENCE INFORMATION
This function calls:
Data Returns Data of a TSD object
Name Returns name propery of object
length Returns number of elements in tsa (overoads length function)
size Return the size of the data component (overoad of the size function)
This function is called by:
CrossCorr Computes cross-correlation between TSD objects
FindPeaks Get peaks in data
Restrict Restrict TSD to a new timestamp
abs Absolute value of the data
cat Concatenation of TSD objects
classify Breaks a TSD object in many tsds according to the value of data
find Selects points in a TSD object based on conditions
horzcat Horizontal concatenation of TSDs (overload of the [a, b] operator)
instantRate Computes instantaneous rate as the inverse of inter-event interval
interp_missing Interpolate missing values in continuously sampled tsd
intervalCount Counts instances of tsa in each subset of an interval
intervalFun im = intervalFun(tsa, is, func, options) computes mean of tsa data in each of the intervals in isw
intervalMean Computes mean of of data in each of subset of a given interval
intervalRate Returns rates of a TSD in each subset of an interval
intervalSplit Returns a cell array of tsd object, one for each subset of a given interval
max Returns the maximal value(s) and time(s) of a TSD object (overoads the max function)
mean
minus Overload of the - operator
peaks Get peaks in data
plus Overload of the + operator
rdivide Overload of the ./ operator for two tsd objects
realign Realign timestamps
smooth Smooth a TSD
subset Returns tsd of a subset of input
threshold Threshold crossings
timeDeriv TimeDerivative of a tsd
times Overload of the .* operator
triggeredMeanData Event-triggered mean of the Data component, triggered on events (TODO)
SOURCE CODE
function tsa = tsd(t, Data, varargin)
% Constructor of TSD object
%
%      USAGE:
%      tsa = tsd(t,data, 'optionName1', optionValue1,...)
%
%  tsd is a class of "timestamped arrays"
%  composed of an array of timestamp (column vector), and an array of data
%  associated to each timestamp (first index corresponding to time).
%  data maybe empty, for 0-dimensional data (for example ts
%  data). Othewise first dimension must be same as length of timestamp
%  vector
%  timestamps are assumed to be sorted. If this is not the case, the
%  constructor failes, unless the fixOrder option is set
%  options may include the following:
%  'TimeUnits' - the unit in which the time is expressed (defaults to
%           ts=1/10000s)
%  'DataUnits' - the unit in which data are expressed (for the moment same
%           for all the data)
%  'fixOrder'    - if set to nonzero, constructor will reorder the timestamps,
%            in the case they are not sorted.
% ADR
% version L4.0
% status: PROMOTED
% version by Francesco P. Battaglia 2004
if nargin == 0
 tsa.time_unit = time_units('ts');
 tsa.data_unit = units('none','none');
 tsa.t = NaN;
 tsa.data = NaN;
 tsa.name = '';
 tsa = class(tsa, 'tsd');
 return
end
if nargin < 2
  error('tsd constructor must be called with T, Data');
end
% default option values
fixOrder = 0;
defined_options = ...
    dictArray({ { 'TimeUnits', { time_units('ts'), {'units', 'char' } } },
        { 'DataUnits', { units('none', 'none'), { 'units' } } },
        { 'fixOrder', { 0, { 'numeric' } } },
        { 'keepUnordered', { 0, { 'numeric' } } },
            { 'Name', { '', { 'char' } } } } );
opt_varargin = varargin;
getOpt;
tsa.time_unit = time_units(TimeUnits);
tsa.data_unit = DataUnits;
if isempty(t)
  t = zeros(0,1);
end
if all(size(t) ~= 1)
  error('t must b row or column error');
end
if size(Data, 1) ~= length(t) & (~isempty(Data))
  error('Data must be N x X x Y x ..., where N is length(t), or empty');
end
t = t(:);
if any(diff(t) < 0)
  if fixOrder
    [t, ix] = sort(t);
    Data = SelectAlongFirstDimension(Data, ix);
  elseif ~keepUnordered
    error('timestamps are not sorted!');
  end
end
tsa.t = t;
tsa.data = Data;
tsa.name = Name;
tsa = class(tsa, 'tsd');