Description of unique
Home > @tsd > unique.m
unique
PURPOSE
Eliminates points with the same timestamps
SYNOPSIS
function t = unique(tsa)
DESCRIPTION
  Eliminates points with the same timestamps
      USAGE:
      t = unique(tsa)
      INPUTS:
      tsa: a tsd object
CROSS-REFERENCE INFORMATION
This function calls:
Range Returns TSD timestamps
subset Returns tsd of a subset of input
unique Eliminates points with the same timestamps
This function is called by:
thresholdHysteresis Hysteresis thresholding
unique Eliminates points with the same timestamps
SOURCE CODE
function t = unique(tsa)
%  Eliminates points with the same timestamps
%
%      USAGE:
%      t = unique(tsa)
%
%      INPUTS:
%      tsa: a tsd object
% copyright (c) 2006 Francesco P. Battaglia
% This software is released under the GNU GPL
% www.gnu.org/copyleft/gpl.html
 tim = Range(tsa);
 [tt, ix, j] = unique(tim);
 t = subset(tsa, ix);